layout = {
	['icon_structure2_antiartillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_engineer_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_transport_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_shield_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_naval_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antimissile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_missile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_mass_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_land_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_intel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_energy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_counterintel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_artillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antinavy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antiair_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_air_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_directfire_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_generic_selected'] = {left = 8, top = 8, width = 16, height = 20, },
}
