layout = {
	['icon_structure_antiartillery_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_engineer_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_transport_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_shield_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_naval_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antimissile_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_missile_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_mass_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_land_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_intel_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_energy_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_counterintel_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_artillery_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antinavy_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antiair_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_air_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_directfire_over'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_generic_over'] = {left = 10, top = 10, width = 12, height = 12, },
}
