layout = {
	['icon_structure1_antiartillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_engineer_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_transport_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_shield_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_naval_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antimissile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_missile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_mass_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_land_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_intel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_energy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_counterintel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_artillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antinavy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antiair_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_air_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_directfire_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_generic_selected'] = {left = 8, top = 8, width = 16, height = 20, },
}
