layout = {
	['icon_structure_antiartillery_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_engineer_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_transport_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_shield_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_naval_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antimissile_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_missile_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_mass_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_land_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_intel_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_energy_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_counterintel_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_artillery_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antinavy_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_antiair_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_air_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_directfire_rest'] = {left = 10, top = 10, width = 12, height = 12, },
	['icon_structure_generic_rest'] = {left = 10, top = 10, width = 12, height = 12, },
}
