layout = {
	['icon_structure_antiartillery_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_engineer_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_transport_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_shield_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_naval_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antimissile_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_missile_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_mass_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_land_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_intel_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_energy_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_counterintel_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_artillery_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antinavy_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antiair_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_air_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_directfire_selected'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_generic_selected'] = {left = 8, top = 8, width = 16, height = 16, },
}
