layout = {
	['icon_structure3_antiartillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_engineer_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_transport_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_shield_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_naval_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antimissile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_missile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_mass_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_land_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_intel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_energy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_counterintel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_artillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antinavy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antiair_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_air_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_directfire_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_generic_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
}
