layout = {
	['icon_structure3_antiartillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_engineer_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_transport_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_shield_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_naval_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antimissile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_missile_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_mass_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_land_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_intel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_energy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_counterintel_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_artillery_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antinavy_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_antiair_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_air_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_directfire_selected'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure3_generic_selected'] = {left = 8, top = 8, width = 16, height = 20, },
}
