layout = {
	['icon_structure_antiartillery_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_engineer_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_transport_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_shield_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_naval_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antimissile_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_missile_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_mass_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_land_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_intel_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_energy_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_counterintel_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_artillery_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antinavy_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_antiair_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_air_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_directfire_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
	['icon_structure_generic_selectedover'] = {left = 8, top = 8, width = 16, height = 16, },
}
