layout = {
	['icon_structure2_antiartillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_engineer_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_transport_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_shield_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_naval_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antimissile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_missile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_mass_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_land_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_intel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_energy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_counterintel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_artillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antinavy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_antiair_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_air_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_directfire_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure2_generic_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
}
