layout = {
	['icon_structure1_antiartillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_engineer_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_transport_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_shield_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_naval_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antimissile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_missile_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_mass_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_land_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_intel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_energy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_counterintel_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_artillery_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antinavy_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_antiair_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_air_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_directfire_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
	['icon_structure1_generic_selectedover'] = {left = 8, top = 8, width = 16, height = 20, },
}
