---@meta

---@class BeamBlueprint : EmitterBlueprint
---@field Length number                Total length of beam
---@field Lifetime number              Lifetime of the emitter
---@field Thickness number             Thickness of the beam
---@field TextureName FileName         Filename of texture
---@field StartColor NamedQuaternion   RGBA start color of beam
---@field EndColor NamedQuaternion     RGBA end color of beam
---@field UShift number                U Texture shift of beam texture
---@field VShift number                V Texture shift of beam texture
---@field RepeatRate number            How often the texture repeats per ogrid blendmode of this beam
