---@meta

---@alias BlueprintId string

---@class Blueprint
--- The unique id of this blueprint. For units, this field is autogenerated from `Source` if not
--- already present. If a blueprint is loaded that has the same id as one already loaded, it
--- overrides it unless `Merge = true` is also set. This is typically what happens for mods, e.g.
---     BlueprintId = "uel0101",
---     Merge = true,
--- would let you change the blueprint of the Snoop UEF Land Scout without needing to add everything
--- in the original definition (which could change or be modified by other mods).
---@field BlueprintId BlueprintId
--- Setting `Merge = true` will make the blueprint definition merge with an already existing one
--- given by `BlueprintId` (which must also be set to an existing blueprint id).
---@field Merge? boolean
--- the file the blueprint was originally defined in
---@field Source string

---@alias SoundLodCutoff
---| "DefaultLodCutoff"
---| "UnitMove_LodCutoff"
---| "Weapon_LodCutoff"
---| "WeaponBig_LodCutoff"

---@class SoundBlueprint
--- which sound bank to use
---@field Bank string
--- the sound cue inside of the sound bank to use
---@field Cue string
--- unknown usage
---@field LodCutoff SoundLodCutoff
