MarkerTemplates = {

-- // Pre-existing marker types, ported to the template definition file

    ['Blank Marker'] = {
		prop = "/env/common/props/markers/M_Blank_prop.bp",
		color = "ff800080",
    },
    ['Mass'] = {
        resource = true,
        amount = 100,
        size = 1,
        editorIcon = "/textures/editor/marker_mass.bmp",
		prop = "/env/common/props/markers/M_Mass_prop.bp",
		color = "ff808080",
    },
    ['Hydrocarbon'] = {
        resource = true,
        amount = 100,
        size = 3,
		prop = "/env/common/props/markers/M_Hydrocarbon_prop.bp",
		color = "ff008000",
    },
    ['Combat Zone'] = {
        hint = true,
		prop = "/env/common/props/markers/M_CombatZone_prop.bp",
		color = "ff800000",
    },
    ['Defensive Point'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Defensive_prop.bp",
		color = "ff008000",
    },
    ['Effect'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Defensive_prop.bp",
        EffectTemplate = "SmokePlumeLightDensityMed01",        
		scale = 1.0,
		offset = VECTOR3(0,0,0),
		color = "ffbffcd0",
    },    
    ['Expansion Area'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Expansion_prop.bp",
		color = "ff008080",
    },
    ['Large Expansion Area'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Expansion_prop.bp",
		color = "ffff0080",
    },
    ['Naval Area'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Expansion_prop.bp",
		color = "ff0000FF",
    },
    ['Naval Defensive Point'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Defensive_prop.bp",
		color = "ff0080FF",
    },
    ['Naval Rally Point'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Defensive_prop.bp",
		color = "ff00FFFF",
    },
    ['Protected Experimental Construction'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Expansion_prop.bp",
		color = "ff0000AA",
    },
    ['Rally Point'] = {
        hint = true,
        prop = "/env/common/props/markers/M_Defensive_prop.bp",
        color = "FF808000",
    },
    ['Island'] = {
        hint = true,
        prop = "/env/common/props/markers/M_CombatZone_prop.bp",
        color = "ff0000AA",
    },
    ['Naval Exclude'] = {
        hint = true,
        prop = "/env/common/props/markers/M_CombatZone_prop.bp",
        color = "ff0000AA",
    },
    ['Weather Definition'] = {
        hint = true,
        prop = "/env/common/props/markers/M_Defensive_prop.bp",
        color = "FF808000",
        MapStyle = "Tundra",        
        WeatherType01 = "SnowClouds",
        WeatherType01Chance = 0.3,
        WeatherType02 = "WhiteThickClouds",
        WeatherType02Chance = 0.3,
        WeatherType03 = "WhitePatchyClouds",
        WeatherType03Chance = 0.3,
        WeatherType04 = "None",
        WeatherType04Chance = 0.1,
        WeatherDriftDirection = VECTOR3(1,0,0),
    }, 
    ['Weather Generator'] = {
        hint = true,
        prop = "/env/common/props/markers/M_Defensive_prop.bp",
        color = "FF808000",
        cloudSpread = 150.0,        
        cloudCount = 10.0,        
        cloudCountRange = 0,
        cloudHeight = 180.0,        
        cloudHeightRange = 15.0,        
        cloudEmitterScale = 1.0,
		cloudEmitterScaleRange = 0.0,
        ForceType = "None",
		spawnChance = 1.0,
    },    
    ['Camera Info'] = {
        editorIcon = "/textures/editor/marker_mass.bmp",
        zoom = 0.0,
        canSyncCamera = true,
        canSetCamera = true,
		prop = "/env/common/props/markers/M_Camera_prop.bp",
		color = "ff808000",
    },
    ['Transport Marker'] = {
		prop = "/env/common/props/markers/M_Blank_prop.bp",
		color = "ff80A088",
    },
    ['Naval Link'] = {
		prop = "/env/common/props/markers/M_Blank_prop.bp",
		color = "ffff0000",
    },
    ['Land Path Node'] = {
		hint = true,
		prop = "/env/common/props/markers/M_Path_prop.bp",
		color = "ff00ff00",
		graph = "DefaultLand",
		adjacentTo = "",
    },
    ['Water Path Node'] = {
		hint = true,
		prop = "/env/common/props/markers/M_Path_prop.bp",
		color = "ff0000ff",
		graph = "DefaultWater",
		adjacentTo = "",
    },
    ['Air Path Node'] = {
		hint = true,
		prop = "/env/common/props/markers/M_Path_prop.bp",
		color = "ffffffff",
		graph = "DefaultAir",
		adjacentTo = "",
    },
    ['Amphibious Path Node'] = {
        hint = true,
		prop = "/env/common/props/markers/M_Path_prop.bp",
		color = "ff00ffff",
		graph = "DefaultAmphibious",
		adjacentTo = "",
    },
}
