name: Feature request
description: Create a feature request to discuss with the Game team
title: ' '
labels: ['status: novel issue']

body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Expected Behavior
      description: If applicable, a clear and concise description of what you expect to happen in various scenario's.
    validations:
      required: false
  - type: textarea
    id: images
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your feature.
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        _This feature request will be read by people that are unable to look into your thoughts - this request is all they have to determine the viability of the feature. The more precise your request, the easier it becomes for us to help you._
