name: Contributors template
description: Template for an extensive description, to enable other contributors to work on a feature.
labels: ["status: novel issue"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: action
    attributes:
      label: Course of Action
  - type: textarea
    id: test
    attributes:
      label: Test Plan
  - type: textarea
    id: learning
    attributes:
      label: Learning Goals
  - type: textarea
    id: progress
    attributes:
      label: Progress
