name: Unit Visual Improvements
description: Suggest visual improvements to a unit
title: "[Unit Improvements]: "
labels: ["area: graphics"]

body:
  # Intro
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time in making a Feature Request.

        - This repository is maintained by volunteers, it may take a while for them to come back to you.
        - Remember to include sufficient details and context.
        - If you have multiple Idea's or suggestions, please submit them in separate issues.
        - We accept pull requests. If you know how to fix it - go ahead!

  # Faction Selection
  - type: dropdown
    id: faction
    attributes:
      label: Which Faction is the Unit From?
      options:
        - UEF
        - Aeon
        - Cybran
        - Seraphim
      default: 0
    validations:
      required: true

  # Unit Name
  - type: input
    id: unitID
    attributes:
      label: Name of Unit
      description: User the Blueprint Identifier of the unit (url0001).
    validations:
      required: true

  # Lua Script
  - type: textarea
    id: script
    attributes:
      label: Lua Script Issues
    validations:
      required: false

  # Effects
  - type: checkboxes
    id: effects
    attributes:
      label: Effect Related Issues
      options:
        - label: Tracks are correct (if applicable)
        - label: Footfalls are correct (if applicable)
  - type: textarea
    id: effectsAdditional
    attributes:
      label: Additional Effect Issues
    validations:
      required: false

  #  Texture
  - type: checkboxes
    id: texture
    attributes:
      label: Texture Related Issues
      options:
        - label: Correct albedo intensity
        - label: Correct team color channel
        - label: Correct roughness channel
        - label: Correct metallic channel(s)
        - label: Correct normals
  - type: textarea
    id: textureAdditional
    attributes:
      label: Additional Texture Issues
    validations:
      required: false

  # Mesh/Bone
  - type: checkboxes
    id: mesh
    attributes:
      label: Mesh/Bone Related Issues
      options:
        - label: Bones for target recoil exist
        - label: Bones for targeting exist (only relevant for large units)
        - label: LOD1 exists
        - label: LOD2 exists (optionally)
        - label: LOD3 exists (optionally)
  - type: textarea
    id: meshAdditional
    attributes:
      label: Additional Mesh/Bone Issues
    validations:
      required: false

  # Relevant Shaders
  - type: markdown
    attributes:
      value: |
        You can find all relevant shaders in [mesh.fx](/effects/mesh.fx).

          - Mesh shader techniques: `Insect_HighFidelity` / `Insect_MedFidelity` / `Insect_LowFidelity`
          - Shield shader techniques: `ShieldCybran_MedFidelity` / `ShieldCybran_LowFidelity`

        ## Relevant texture interpretations

        | Mesh shaders | R        | G         | B        | A                                           |
        | ------------ | -------- | --------- | -------- | ------------------------------------------- |
        | Albedo       | R        | G         | B        | Unused                                      |
        | Normals      | Y (copy) | Y         | Y (copy) | X                                           |
        | Spec         | Metallic | Roughness | Emission | Team color / Metallic + roughness reduction |

        Relevant details to individual channels for the high-fidelity (PBR) preset:

          - Albedo.R = Red channel of albedo
          - Albedo.G = Green channel of albedo
          - Albedo.B = Blue channel of albedo
          - Albedo.A = Unused
          
          - Normals.R = Copied Y direction (to prevent compression artifacts)
          - Normals.G = Y direction of normals in tangent space
          - Normals.B = Copied Y direction (to prevent compression artifacts)
          - Normals.A = X direction of normals in tangent space
          
          - Spec.R = Metallic
          - Spec.G = Roughness and increase to metallic if the value is larger than 0.1
          - Spec.B = Emission
          - Spec.A = Team color and it decreases metallic
