
contact_links:
    - name: FAForever Discord Server
      url: https://discord.gg/GEseYDXVRA
      about: Chat with members of the player community, get help with playing the game, and ask the developers questions!