-- This file outlines the interaction between the 'command' (Bound to a key) and the behaviour of that command
-- format is:
--  key - The string referenced by a bound key
--  action - The console command to execute when the key is pressed
--  category - The category to list this action under in the key assign dialog
--  order - The sort order to list this action under its category
--  keyRepeat - A boolean flag that dictates when an action is one that can be held to extend its effect (eg - Zoom)

debugKeyActions = {
    ['debug_navpath'] = {action = 'dbg navpath',
        category = 'debug', order = 1,},
    ['debug_create_unit'] = {action = 'PopupCreateUnitMenu',
        category = 'debug', order = 1,},
    ['debug_teleport'] = {action = 'TeleportSelectedUnits',
        category = 'debug', order = 1,},
    ['debug_run_opponent_AI'] = {action = 'AI_RunOpponentAI',
        category = 'debug', order = 1,},
    ['debug_blingbling'] = {action = 'BlingBling',
        category = 'debug', order = 1,},
    ['debug_destroy_units'] = {action = 'DestroySelectedUnits',
        category = 'debug', order = 1,},
    ['debug_graphics_fidelity_0'] = {action = 'graphics_Fidelity 0',
        category = 'debug', order = 1,},
    ['debug_graphics_fidelity_2'] = {action = 'graphics_Fidelity 2',
        category = 'debug', order = 1,},
    ['debug_scenario_method_f3'] = {action = 'ScenarioMethod OnF3',
        category = 'debug', order = 1,},
    ['debug_scenario_method_shift_f3'] = {action = 'ScenarioMethod OnShiftF3',
        category = 'debug', order = 1,},
    ['debug_scenario_method_ctrl_f3'] = {action = 'ScenarioMethod OnCtrlF3',
        category = 'debug', order = 1,},
    ['debug_scenario_method_shift_f4'] = {action = 'ScenarioMethod OnShiftF4',
        category = 'debug', order = 1,},
    ['debug_scenario_method_ctrl_f4'] = {action = 'ScenarioMethod OnCtrlF4',
        category = 'debug', order = 1,},
    ['debug_scenario_method_ctrl_alt_f3'] = {action = 'ScenarioMethod OnCtrlAltF4',
        category = 'debug', order = 1,},
    ['debug_scenario_method_f4'] = {action = 'ScenarioMethod OnF4',
        category = 'debug', order = 1,},
    ['debug_scenario_method_f5'] = {action = 'ScenarioMethod OnF5',
        category = 'debug', order = 1,},
    ['debug_scenario_method_shift_f5'] = {action = 'ScenarioMethod OnShiftF5',
        category = 'debug', order = 1,},
    ['debug_scenario_method_ctrl_f5'] = {action = 'ScenarioMethod OnCtrlF5',
        category = 'debug', order = 1,},
    ['debug_scenario_method_ctrl_alt_f5'] = {action = 'ScenarioMethod OnCtrlAltF5',
        category = 'debug', order = 1,},
    ['debug_campaign_instawin'] = {action = 'ui_lua import("/lua/ui/campaign/campaignmanager.lua").InstaWin()',
        category = 'debug', order = 1,},
    ['debug_create_entity'] = {action = 'SC_CreateEntityDialog',
        category = 'debug', order = 1,},
    ['debug_show_stats'] = {action = 'ShowStats',
        category = 'debug', order = 1,},
    ['debug_show_army_stats'] = {action = 'ShowArmyStats',
        category = 'debug', order = 1,},
    ['debug_toggle_log_window'] = {action = 'WIN_ToggleLogDialog',
        category = 'debug', order = 1,},
    ['debug_open_lua_debugger'] = {action = 'SC_LuaDebugger',
        category = 'debug', order = 1,},
    ['debug_show_frame_stats'] = {action = 'ShowStats frame',
        category = 'debug', order = 1,},
    ['debug_render_wireframe'] = {action = 'ren_ShowWireframe tog',
        category = 'debug', order = 1,},
    ['debug_weapons'] = {action = 'dbg weapons',
        category = 'debug', order = 1,},
    ['debug_grid'] = {action = 'dbg grid',
        category = 'debug', order = 1,},
    ['debug_show_focus_ui_control'] = {action = 'UI_ShowControlUnderMouse tog',
        category = 'debug', order = 1,},
    ['debug_dump_focus_ui_control'] = {action = 'UI_DumpControlsUnderCursor',
        category = 'debug', order = 1,},
    ['debug_dump_ui_controls'] = {action = 'UI_DumpControls',
        category = 'debug', order = 1,},
    ['debug_skeletons'] = {action = 'Ren_Showskeletons',
        category = 'debug', order = 1,},
    ['debug_bones'] = {action = 'Ren_ShowBoneNames',
        category = 'debug', order = 1,},
    ['debug_redo_console_command'] = {action = 'CON_ExecuteLastCommand',
        category = 'debug', order = 1,},
    ['debug_copy_units'] = {action = 'CopySelectedUnitsToClipboard',
        category = 'debug', order = 1,},
    ['debug_paste_units'] = {action = 'ExecutePasteBuffer',
        category = 'debug', order = 1,},
    ['debug_nodamage'] = {action = 'Nodamage',
        category = 'debug', order = 1,},
    ['debug_show_emmitter_window'] = {action = 'EFX_CreateEmitterWindow',
        category = 'debug', order = 1,},
    ['debug_sally_shears'] = {action = 'SallyShears',
        category = 'debug', order = 1,},
    ['debug_collision'] = {action = 'dbg Collision',
        category = 'debug', order = 1,},
    ['debug_pause_single_step'] = {action = 'WLD_SingleStep',
        category = 'game', order = 1,},
    ['debug_restart_session'] = {action = 'UI_Lua RestartSession()',
        category = 'debug', order = 1,},
    ['debug_toggle_pannels'] = {action = 'UI_ToggleGamePanels',
        category = 'debug', order = 2,},
}
