-- This file outlines the interaction between the 'command' (Bound to a key) and the behaviour of that command
-- format is:
--  key - The string referenced by a bound key
--  action - The console command to execute when the key is pressed
--  category - The category to list this action under in the key assign dialog
--  order - The sort order to list this action under its category
--  keyRepeat - A boolean flag that dictates when an action is one that can be held to extend its effect (eg - Zoom)

keyActions = {
    ['escape'] = {action = 'UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()',
        category = 'ui', order = 1,},
    ['pause'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").TogglePause()',
        category = 'ui', order = 3,},
    ['cap_frame'] = {action = 'Dump_Frame',
        category = 'ui', order = 4,},
    ['toggle_lifebars'] = {action = 'UI_RenderUnitBars',
        category = 'ui', order = 1,},
    ['tog_military'] = {action = 'UI_Lua import("/lua/ui/game/multifunction.lua").ToggleMilitary()',
        category = 'ui', order = 5,},
    ['tog_defense'] = {action = 'UI_Lua import("/lua/ui/game/multifunction.lua").ToggleDefense()',
        category = 'ui', order = 6,},
    ['tog_econ'] = {action = 'UI_Lua import("/lua/ui/game/multifunction.lua").ToggleEconomy()',
        category = 'ui', order = 7,},
    ['rename'] = {action = 'UI_ShowRenameDialog',
        category = 'ui', order = 10,},
    ['split_screen_enable'] = {action = 'UI_Lua import("/lua/ui/game/borders.lua").SplitMapGroup(true)',
        category = 'ui', order = 13,},
    ['split_screen_disable'] = {action = 'UI_Lua import("/lua/ui/game/borders.lua").SplitMapGroup(false)',
        category = 'ui', order = 14,},
    ['switch_layout_up'] = {action = 'UI_RotateLayout +',
        category = 'ui', order = 17,},
    ['switch_layout_down'] = {action = 'UI_RotateLayout -',
        category = 'ui', order = 18,},
    ['switch_skin_down'] = {action = 'UI_RotateSkin -',
        category = 'ui', order = 17,},
    ['switch_skin_up'] = {action = 'UI_RotateSkin +',
        category = 'ui', order = 17,},
    ['toggle_key_bindings'] = {action = 'UI_Lua import("/lua/ui/dialogs/keybindings.lua").CreateUI()',
        category = 'ui', order = 6,},
    ['toggle_notify_customiser'] = {action = 'UI_Lua import("/lua/ui/notify/customiser.lua").CreateUI()',
        category = 'ui', order = 6,},
    ['toggle_score_screen'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").ToggleScore()',
        category = 'ui', order = 1,},
    ['quick_save'] = {action = 'UI_Lua import("/lua/ui/game/gamemain.lua").QuickSave(LOC("<LOC QuickSave>QuickSave"))',
        category = 'ui', order = 23,},
    ['toggle_diplomacy_screen'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").ToggleTab("diplomacy")',
        category = 'ui', order = 4,},
    ['ping_alert'] = {action = 'UI_Lua import("/lua/ui/game/ping.lua").DoPing("alert")',
        category = 'ui', order = 22,},
    ['ping_move'] = {action = 'UI_Lua import("/lua/ui/game/ping.lua").DoPing("move")',
        category = 'ui', order = 23,},
    ['ping_attack'] = {action = 'UI_Lua import("/lua/ui/game/ping.lua").DoPing("attack")',
        category = 'ui', order = 24,},
    ['ping_marker'] = {action = 'UI_Lua import("/lua/ui/game/ping.lua").DoPing("marker")',
        category = 'ui', order = 25,},
    ['toggle_main_menu'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").ToggleTab("main")',
        category = 'ui', order = 4,},
    ['toggle_disconnect_screen'] = {action = 'UI_Lua import("/lua/ui/game/connectivity.lua").CreateUI()',
        category = 'ui', order = 21,},
    ['toggle_reclaim_labels'] = {action = 'UI_Lua import("/lua/ui/game/reclaim.lua").ToggleReclaim()',
        category = 'ui'},
    ['group1'] = {action = 'UI_ApplySelectionSet 1',
        category = 'selection', order = 1,},
    ['group2'] = {action = 'UI_ApplySelectionSet 2',
        category = 'selection', order = 2,},
    ['group3'] = {action = 'UI_ApplySelectionSet 3',
        category = 'selection', order = 3,},
    ['group4'] = {action = 'UI_ApplySelectionSet 4',
        category = 'selection', order = 4,},
    ['group5'] = {action = 'UI_ApplySelectionSet 5',
        category = 'selection', order = 5,},
    ['group6'] = {action = 'UI_ApplySelectionSet 6',
        category = 'selection', order = 6,},
    ['group7'] = {action = 'UI_ApplySelectionSet 7',
        category = 'selection', order = 7,},
    ['group8'] = {action = 'UI_ApplySelectionSet 8',
        category = 'selection', order = 8,},
    ['group9'] = {action = 'UI_ApplySelectionSet 9',
        category = 'selection', order = 9,},
    ['group0'] = {action = 'UI_ApplySelectionSet 0',
        category = 'selection', order = 10,},
    ['set_group1'] = {action = 'UI_MakeSelectionSet 1',
        category = 'selection', order = 11,},
    ['set_group2'] = {action = 'UI_MakeSelectionSet 2',
        category = 'selection', order = 12,},
    ['set_group3'] = {action = 'UI_MakeSelectionSet 3',
        category = 'selection', order = 13,},
    ['set_group4'] = {action = 'UI_MakeSelectionSet 4',
        category = 'selection', order = 14,},
    ['set_group5'] = {action = 'UI_MakeSelectionSet 5',
        category = 'selection', order = 15,},
    ['set_group6'] = {action = 'UI_MakeSelectionSet 6',
        category = 'selection', order = 16,},
    ['set_group7'] = {action = 'UI_MakeSelectionSet 7',
        category = 'selection', order = 17,},
    ['set_group8'] = {action = 'UI_MakeSelectionSet 8',
        category = 'selection', order = 18,},
    ['set_group9'] = {action = 'UI_MakeSelectionSet 9',
        category = 'selection', order = 19,},
    ['set_group0'] = {action = 'UI_MakeSelectionSet 0',
        category = 'selection', order = 20,},
    ['append_group1'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(1)',
        category = 'selection', order = 21,},
    ['append_group2'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(2)',
        category = 'selection', order = 22,},
    ['append_group3'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(3)',
        category = 'selection', order = 23,},
    ['append_group4'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(4)',
        category = 'selection', order = 24,},
    ['append_group5'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(5)',
        category = 'selection', order = 25,},
    ['append_group6'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(6)',
        category = 'selection', order = 26,},
    ['append_group7'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(7)',
        category = 'selection', order = 27,},
    ['append_group8'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(8)',
        category = 'selection', order = 28,},
    ['append_group9'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(9)',
        category = 'selection', order = 29,},
    ['append_group0'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").AppendSetToSelection(0)',
        category = 'selection', order = 30,},
    ['fac_group1'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(1)',
        category = 'selection', order = 31,},
    ['fac_group2'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(2)',
        category = 'selection', order = 32,},
    ['fac_group3'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(3)',
        category = 'selection', order = 33,},
    ['fac_group4'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(4)',
        category = 'selection', order = 34,},
    ['fac_group5'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(5)',
        category = 'selection', order = 35,},
    ['fac_group6'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(6)',
        category = 'selection', order = 36,},
    ['fac_group7'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(7)',
        category = 'selection', order = 37,},
    ['fac_group8'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(8)',
        category = 'selection', order = 38,},
    ['fac_group9'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(9)',
        category = 'selection', order = 39,},
    ['fac_group0'] = {action = 'UI_Lua import("/lua/ui/game/selection.lua").FactorySelection(0)',
        category = 'selection', order = 40,},
    ['select_air'] = {action = 'UI_SelectByCategory +excludeengineers AIR MOBILE',
        category = 'selection', order = 41,},
    ['select_naval'] = {action = 'UI_SelectByCategory +excludeengineers NAVAL MOBILE',
        category = 'selection', order = 42,},
    ['select_land'] = {action = 'UI_SelectByCategory +excludeengineers LAND MOBILE',
        category = 'selection', order = 43,},
    ['select_all_units_of_same_type'] = {action = 'UI_ExpandCurrentSelection',
        category = 'selection', order = 44,},
    ['select_engineers'] = {action = 'UI_SelectByCategory ENGINEER',
        category = 'selection', order = 45,},
    ['goto_engineer'] = {action = 'UI_SelectByCategory +nearest +idle +goto ENGINEER',
        category = 'selection', order = 46,},
    ['select_idle_engineer'] = {action = 'UI_SelectByCategory +nearest +idle ENGINEER',
        category = 'selection', order = 47,},
    ['cycle_engineers'] = {action = 'UI_Lua import("/lua/ui/game/avatars.lua").GetEngineerGeneric()',
        category = 'selection', order = 48,},
    ['goto_commander'] = {action = 'UI_SelectByCategory +nearest +goto COMMAND',
        category = 'selection', order = 49,},
    ['select_commander'] = {action = 'UI_SelectByCategory +nearest COMMAND',
        category = 'selection', order = 50,},
    ['select_all'] = {action = 'UI_SelectByCategory ALLUNITS',
        category = 'selection', order = 51,},
    ['select_all_onscreen'] = {action = 'UI_SelectByCategory +inview ALLUNITS',
        category = 'selection', order = 52,},
    ['select_all_eng_onscreen'] = {action = 'UI_SelectByCategory +inview ENGINEER',
        category = 'selection', order = 53,},
    ['select_all_factory_onscreen'] = {action = 'UI_SelectByCategory +inview FACTORY',
        category = 'selection', order = 54,},
    ['select_nearest_factory'] = {action = 'UI_SelectByCategory +nearest FACTORY',
        category = 'selection', order = 55,},
    ['select_nearest_land_factory'] = {action = 'UI_SelectByCategory +nearest LAND FACTORY',
        category = 'selection', order = 56,},
    ['select_nearest_air_factory'] = {action = 'UI_SelectByCategory +nearest AIR FACTORY',
        category = 'selection', order = 57,},
    ['select_nearest_naval_factory'] = {action = 'UI_SelectByCategory +nearest NAVAL FACTORY',
        category = 'selection', order = 58,},
    ['next_cam_position'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").RecallCameraPos()',
        category = 'camera', order = 1,},
    ['add_cam_position'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").SaveCameraPos()',
        category = 'camera', order = 2,},
    ['rem_cam_position'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").RemoveCamPos()',
        category = 'camera', order = 3,},
    ['zoom_in'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").ZoomIn(.02)',
        category = 'camera', order = 4, keyRepeat = true,},
    ['zoom_out'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").ZoomOut(.02)',
        category = 'camera', order = 5, keyRepeat = true,},
    ['zoom_in_fast'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").ZoomIn(.08)',
        category = 'camera', order = 6,},
    ['zoom_out_fast'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").ZoomOut(.08)',
        category = 'camera', order = 7,},
    ['track_unit'] = {action = 'UI_TrackUnit WorldCamera',
        category = 'camera', order = 8,},
    ['track_unit_minimap'] = {action = 'UI_TrackUnit MiniMap',
        category = 'camera', order = 9,},
    ['track_unit_second_mon'] = {action = 'UI_TrackUnit CameraHead2',
        category = 'camera', order = 10,},
    ['reset_camera'] = {action = 'UI_Lua import("/lua/ui/game/zoomslider.lua").ToggleWideView()',
        category = 'camera', order = 11,},
    ['cam_free'] = {action = 'Cam_Free',
        category = 'camera', order = 13,},
    ['repair'] = {action = 'StartCommandMode order RULEUCC_Repair',
        category = 'orders', order = 9,},
    ['reclaim'] = {action = 'StartCommandMode order RULEUCC_Reclaim',
        category = 'orders', order = 7,},
    ['patrol'] = {action = 'StartCommandMode order RULEUCC_Patrol',
        category = 'orders', order = 5,},
    ['attack'] = {action = 'StartCommandMode order RULEUCC_Attack',
        category = 'orders', order = 13,},
    ['capture'] = {action = 'StartCommandMode order RULEUCC_Capture',
        category = 'orders', order = 21,},
    ['stop'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").Stop()',
        category = 'orders', order = 1,},
    ['soft_stop'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").SoftStop()',
        category = 'orders', order = 1,},
    ['dive'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").ToggleDiveOrder()',
        category = 'orders', order = 27,},
    ['ferry'] = {action = 'StartCommandMode order RULEUCC_Ferry',
        category = 'orders', order = 19,},
    ['guard'] = {action = 'StartCommandMode order RULEUCC_Guard',
        category = 'orders', order = 17,},
    ['transport'] = {action = 'StartCommandMode order RULEUCC_Transport',
        category = 'orders', order = 3,},
    ['launch_tactical'] = {action = 'StartCommandMode order RULEUCC_Tactical',
        category = 'orders', order = 25,},
    ['overcharge'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").EnterOverchargeMode()',
        category = 'orders', order = 23,},
    ['move'] = {action = 'StartCommandMode order RULEUCC_Move',
        category = 'orders', order = 11,},
    ['nuke'] = {action = 'StartCommandMode order RULEUCC_Nuke',
        category = 'orders', order = 15,},
    ['shift_repair'] = {action = 'StartCommandMode order RULEUCC_Repair',
        category = 'orders', order = 10,},
    ['shift_reclaim'] = {action = 'StartCommandMode order RULEUCC_Reclaim',
        category = 'orders', order = 8,},
    ['shift_patrol'] = {action = 'StartCommandMode order RULEUCC_Patrol',
        category = 'orders', order = 6,},
    ['shift_attack'] = {action = 'StartCommandMode order RULEUCC_Attack',
        category = 'orders', order = 14,},
    ['shift_capture'] = {action = 'StartCommandMode order RULEUCC_Capture',
        category = 'orders', order = 22,},
    ['shift_stop'] = {action = 'IssueCommand Stop',
        category = 'orders', order = 2,},
    ['shift_dive'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").ToggleDiveOrder()',
        category = 'orders', order = 28,},
    ['shift_ferry'] = {action = 'StartCommandMode order RULEUCC_Ferry',
        category = 'orders', order = 20,},
    ['shift_guard'] = {action = 'StartCommandMode order RULEUCC_Guard',
        category = 'orders', order = 18,},
    ['shift_transport'] = {action = 'StartCommandMode order RULEUCC_Transport',
        category = 'orders', order = 4,},
    ['shift_launch_tactical'] = {action = 'StartCommandMode order RULEUCC_Tactical',
        category = 'orders', order = 26,},
    ['shift_overcharge'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").EnterOverchargeMode()',
        category = 'orders', order = 24,},
    ['shift_move'] = {action = 'StartCommandMode order RULEUCC_Move',
        category = 'orders', order = 12,},
    ['shift_nuke'] = {action = 'StartCommandMode order RULEUCC_Nuke',
        category = 'orders', order = 16,},
    ['toggle_build_mode'] = {action = 'UI_Lua import("/lua/ui/game/buildmode.lua").ToggleBuildMode()',
        category = 'orders', order = 30,},
    ['pause_unit'] = {action = 'UI_Lua import("/lua/ui/game/construction.lua").ToggleUnitPause()',
        category = 'orders', order = 31,},
    ['mode'] = {action = 'UI_Lua import("/lua/ui/game/orders.lua").CycleRetaliateStateUp()',
        category = 'orders', order = 32,}, --cut?
    ['suicide'] = {action = 'UI_Lua import("/lua/ui/game/confirmunitdestroy.lua").ConfirmUnitDestruction(false)',
        category = 'orders', order = 29,},
    ['spreadattack'] = {action = 'UI_Lua import("/lua/spreadattack.lua").SpreadAttack()',
        category = 'orders', order = 33,},
    ['shift_spreadattack'] = {action = 'UI_Lua import("/lua/spreadattack.lua").SpreadAttack()',
        category = 'orders', order = 34,},
    ['decrease_game_speed'] = {action = 'UI_Lua import("/lua/ui/uimain.lua").DecreaseGameSpeed()',
        category = 'game', order = 1,},
    ['increase_game_speed'] = {action = 'UI_Lua import("/lua/ui/uimain.lua").IncreaseGameSpeed()',
        category = 'game', order = 2,},
    ['reset_game_speed'] = {action = 'WLD_ResetSimRate',
        category = 'game', order = 3,},
    ['chat_page_up'] = {action = 'UI_Lua import("/lua/ui/game/chat.lua").ChatPageUp(10)',
        category = 'chat', order = 2,},
    ['chat_page_down'] = {action = 'UI_Lua import("/lua/ui/game/chat.lua").ChatPageDown(10)',
        category = 'chat', order = 3,},
    ['chat_line_up'] = {action = 'UI_Lua import("/lua/ui/game/chat.lua").ChatPageUp(1)',
        category = 'chat', order = 4,},
    ['chat_line_down'] = {action = 'UI_Lua import("/lua/ui/game/chat.lua").ChatPageDown(1)',
        category = 'chat', order = 5,},
    ['show_fps'] = {action = 'UI_Lua import("/lua/debug/uidebug.lua").ShowFPS()',
        category = 'ui', order = 1,},
    ['create_build_template'] = {action = 'UI_Lua import("/lua/ui/game/build_templates.lua").CreateBuildTemplate()',
        category = 'selection', order = 100},
    ['show_objective_screen'] = {action = 'UI_Lua import("/lua/ui/game/objectiveDetail.lua").ToggleDisplay()',
        category = 'ui', order = 23},
    ['toggle_repeat_build'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").ToggleRepeatBuild()',
        category = 'orders', order = 1,},
    ['show_enemy_life'] = {action = 'UI_ForceLifbarsOnEnemy',
        category = 'ui', order = 2,},
    ['show_network_stats'] = {action = 'ren_ShowNetworkStats',
        category = 'ui', order = 3,},
    ['toggle_shield'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Shield")',
        category = 'orders', order = 6,},
    ['toggle_weapon'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Weapon")',
        category = 'orders', order = 7,},
    ['toggle_jamming'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Jamming")',
        category = 'orders', order = 8,},
    ['toggle_intel'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Intel")',
        category = 'orders', order = 9,},
    ['toggle_production'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Production")',
        category = 'orders', order = 10,},
    ['toggle_stealth'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Stealth")',
        category = 'orders', order = 11,},
    ['toggle_generic'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Generic")',
        category = 'orders', order = 12,},
    ['toggle_special'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Special")',
        category = 'orders', order = 13,},
    ['toggle_cloak'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleScript("Cloak")',
        category = 'orders', order = 14,},
    ['toggle_all'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleAllScript()',
        category = 'orders', order = 15,},
    ['teleport'] = {action = 'StartCommandMode order RULEUCC_Teleport',
        category = 'orders', order = 5,},
    ['military_overlay'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleOverlay("Military")',
        category = 'ui', order = 16,},
    ['intel_overlay'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleOverlay("Intel")',
        category = 'ui', order = 17,},
    ['select_all_idle_eng_onscreen'] = {action = 'UI_SelectByCategory +inview +idle ENGINEER',
        category = 'selection', order = 18,},
    ['select_all_land_units_onscreen'] = {action = 'UI_SelectByCategory +inview +excludeengineers LAND',
        category = 'selection', order = 18,},
    ['select_all_air_units_onscreen'] = {action = 'UI_SelectByCategory +inview AIR',
        category = 'selection', order = 18,},
    ['select_all_naval_units_onscreen'] = {action = 'UI_SelectByCategory +inview NAVAL',
        category = 'selection', order = 18,},
    ['select_all_similar_units'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetSimilarUnits()',
        category = 'selection', order = 19,},
    ['select_next_land_factory'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetNextLandFactory()',
        category = 'selection', order = 20,},
    ['select_next_air_factory'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetNextAirFactory()',
        category = 'selection', order = 21,},
    ['select_next_naval_factory'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetNextNavalFactory()',
        category = 'selection', order = 22,},
    ['toggle_selectedinfo'] = {action = 'UI_Lua import("/lua/keymap/selectedinfo.lua").ToggleOn()',
        category = 'ui', order = 23,},
    ['toggle_selectedrings'] = {action = 'UI_Lua import("/lua/keymap/selectedinfo.lua").ToggleOverlayOn()',
        category = 'ui', order = 24,},
    ['toggle_cloakjammingstealth'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleCloakJammingStealthScript()',
        category = 'orders', order = 25,},
    ['toggle_intelshield'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").toggleIntelShieldScript()',
        category = 'orders', order = 26,},
    ['toggle_mdf_panel'] = {action = 'UI_Lua import("/lua/ui/game/multifunction.lua").ToggleMFDPanel()',
        category = 'ui', order = 27,},
    ['toggle_tab_display'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").ToggleTabDisplay()',
        category = 'ui', order = 28,},
    ['zoom_pop'] = {action = "UI_Lua import('/lua/ui/game/zoompopper.lua').ToggleZoomPop()",
        category = 'camera', order = 29,},
    ['select_inview_idle_mex'] = {action = 'UI_SelectByCategory +inview +idle MASSEXTRACTION',
        category = 'selection', order = 30,},
    ['select_all_mex'] = {action = 'UI_SelectByCategory MASSEXTRACTION',
        category = 'selection', order = 31,},
    ['select_nearest_idle_lt_mex'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetNearestIdleLTMex()',
        category = 'selection', order = 32,},
    ['acu_select_cg'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()',
        category = 'selection', order = 33,},
    ['acu_append_cg'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").ACUAppendCG()',
        category = 'selection', order = 34,},
    ['select_nearest_idle_eng_not_acu'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").GetNearestIdleEngineerNotACU()',
        category = 'selection', order = 35,},
    ['add_nearest_idle_engineers_seq'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").AddNearestIdleEngineersSeq()',
        category = 'selection', order = 36,},
    ['cycle_idle_factories'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").CycleIdleFactories()',
        category = 'selection', order = 37,},
    ['cycle_unit_types_in_sel'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").CycleUnitTypesInSel()',
        category = 'selection', order = 38,},
    ['create_template_factory'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").CreateTemplateFactory()',
        category = 'selection', order = 39,},
    ['select_gunships'] = {action = 'UI_SelectByCategory AIR GROUNDATTACK',
        category = 'selection', order = 40,},
    ['select_bombers'] = {action = 'UI_SelectByCategory AIR BOMBER',
        category = 'selection', order = 41,},
    ['select_anti_air_fighters'] = {action = 'UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")',
        category = 'selection', order = 42,},
    ['select_nearest_idle_airscout'] = {action = 'UI_SelectByCategory AIR INTELLIGENCE +nearest +idle',
        category = 'selection', order = 42,},
    ['select_all_tml'] = {action = 'UI_SelectByCategory STRUCTURE TACTICALMISSILEPLATFORM',
        category = 'selection', order = 43,},
    ['select_all_stationdrones'] = {action = 'UI_SelectByCategory AIR STATIONASSISTPOD',
        category = 'selection', order = 44,},
    ['select_all_t2_podstations'] = {action = 'UI_SelectByCategory STRUCTURE PODSTAGINGPLATFORM TECH2',
        category = 'selection', order = 44,},
    ['select_all_air_exp'] = {action = 'UI_SelectByCategory AIR EXPERIMENTAL',
        category = 'selection', order = 45,},
    ['select_all_antinavy_subs'] = {action = 'UI_SelectByCategory SUBMERSIBLE OVERLAYANTINAVY',
        category = 'selection', order = 46,},
    ['select_all_land_exp'] = {action = 'UI_SelectByCategory LAND MOBILE OVERLAYDIRECTFIRE EXPERIMENTAL',
        category = 'selection', order = 47,},
    ['select_all_land_indirectfire'] = {action = 'UI_SelectByCategory LAND OVERLAYINDIRECTFIRE',
        category = 'selection', order = 48,},
    ['select_all_land_directfire'] = {action = 'UI_SelectByCategory +excludeengineers LAND OVERLAYDIRECTFIRE',
        category = 'selection', order = 49,},
    ['select_all_air_factories'] = {action = 'UI_SelectByCategory STRUCTURE FACTORY AIR',
        category = 'selection', order = 50,},
    ['select_all_land_factories'] = {action = 'UI_SelectByCategory STRUCTURE FACTORY LAND',
        category = 'selection', order = 51,},
    ['select_all_naval_factories'] = {action = 'UI_SelectByCategory STRUCTURE FACTORY NAVAL',
        category = 'selection', order = 52,},
    ['select_all_t1_engineers'] = {action = 'UI_SelectByCategory LAND TECH1 ENGINEER',
        category = 'selection', order = 53,},
    ['select_all_battleships'] = {action = 'UI_SelectByCategory NAVAL BATTLESHIP',
        category = 'selection', order = 54,},
    ['Render_SelectionSet_Names'] = {action = 'ui_RenderSelectionSetNames',
        category = 'ui', order = 55,},
    ['Render_Custom_Names'] = {action = 'ui_RenderCustomNames',
        category = 'ui', order = 56,},
    ['Render_Unit_Bars'] = {action = 'ui_RenderUnitBars',
        category = 'ui', order = 57,},
    ['Render_Icons'] = {action = 'ui_RenderIcons',
        category = 'ui', order = 58,},
    ['Always_Render_Strategic_Icons'] = {action = 'ui_AlwaysRenderStrategicIcons',
        category = 'ui', order = 59,},
    ['Kill_Selected_Units'] = {action = 'UI_Lua import("/lua/ui/game/confirmunitdestroy.lua").ConfirmUnitDestruction(true)',
        category = 'orders', order = 60,},
    ['Kill_All'] = {action = 'KillAll',
        category = 'orders', order = 61,},
    ['Show_Bandwidth_Usage'] = {action = 'ren_ShowBandwidthUsage',
        category = 'ui', order = 62,},
    ['Execute_Paste_Buffer'] = {action = 'ExecutePasteBuffer',
        category = 'ui', order = 63,},
    ['select_air_no_transport'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").airNoTransports()',
        category = 'selection', order = 64,},
    ['select_air_transport'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").airTransports()',
        category = 'selection', order =65,},
    ['lock_zoom'] = {action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").lockZoom()',
        category = 'camera', order = 666,},

    -- HOTBUILD
    ['builders'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Builders")',
        category = 'hotbuilding', order = 1101,},
    ['sensors'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Sensors")',
        category = 'hotbuilding', order = 1102,},
    ['shields'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Shields")',
        category = 'hotbuilding', order = 1103,},
    ['tmd'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("TMD")',
        category = 'hotbuilding', order = 1104,},
    ['xp'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("XP")',
        category = 'hotbuilding', order = 1105,},
    ['mobilearty'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Mobilearty")',
        category = 'hotbuilding', order = 1106,},
    ['mass'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Mass")',
        category = 'hotbuilding', order = 1107,},
    ['massfab'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("MassFab")',
        category = 'hotbuilding', order = 1108,},
    ['pgen'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Pgen")',
        category = 'hotbuilding', order = 1109,},
    ['templates'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Templates")',
        category = 'hotbuilding', order = 1110,},
    ['engystation'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("EngyStation")',
        category = 'hotbuilding', order = 1111,},
    ['mml'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("MML")',
        category = 'hotbuilding', order = 1112,},
    ['mobileshield'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("MobileShield")',
        category = 'hotbuilding', order = 1113,},
    ['fieldengy'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("FieldEngy")',
        category = 'hotbuilding', order = 1114,},
    ['defense'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Defense")',
        category = 'hotbuilding', order = 1115,},
    ['aa'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("AA")',
        category = 'hotbuilding', order = 1116,},
    ['torpedo'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Torpedo")',
        category = 'hotbuilding', order = 1117,},
    ['arties'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Arties")',
        category = 'hotbuilding', order = 1118,},
    ['tml'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("TML")',
        category = 'hotbuilding', order = 1119,},
    ['upgrades'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Upgrades")',
        category = 'hotbuilding', order = 1120,},

    -- EXTRA
    ['land_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Land_Factory")',
        category = 'hotbuildingExtra', order = 1200,},
    ['air_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Air_Factory")',
        category = 'hotbuildingExtra', order = 1201,},
    ['naval_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Naval_Factory")',
        category = 'hotbuildingExtra', order = 1202,},
    ['quantum_gateway'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Quantum_Gateway")',
        category = 'hotbuildingExtra', order = 1203,},
    ['power_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Power_Generator")',
        category = 'hotbuildingExtra', order = 1204,},
    ['hydrocarbon_power_plant'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Hydrocarbon_Power_Plant")',
        category = 'hotbuildingExtra', order = 1205,},
    ['mass_extractor'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Mass_Extractor")',
        category = 'hotbuildingExtra', order = 1206,},
    ['mass_fabricator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Mass_Fabricator")',
        category = 'hotbuildingExtra', order = 1207,},
    ['energy_storage'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Energy_Storage")',
        category = 'hotbuildingExtra', order = 1208,},
    ['mass_storage'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Mass_Storage")',
        category = 'hotbuildingExtra', order = 1209,},
    ['point_defense'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Point_Defense")',
        category = 'hotbuildingExtra', order = 1210,},
    ['anti_air'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Anti_Air")',
        category = 'hotbuildingExtra', order = 1211,},
    ['tactical_missile_launcher'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Tactical_Missile_Launcher")',
        category = 'hotbuildingExtra', order = 1212,},
    ['torpedo_launcher'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Torpedo_Launcher")',
        category = 'hotbuildingExtra', order = 1213,},
    ['heavy_artillery_installation'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Heavy_Artillery_Installation")',
        category = 'hotbuildingExtra', order = 1214,},
    ['artillery_installation'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Artillery_Installation")',
        category = 'hotbuildingExtra', order = 1215,},
    ['strategic_missile_launcher'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Strategic_Missile_Launcher")',
        category = 'hotbuildingExtra', order = 1216,},
    ['radar_system'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Radar_System")',
        category = 'hotbuildingExtra', order = 1217,},
    ['sonar_system'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Sonar_System")',
        category = 'hotbuildingExtra', order = 1218,},
    ['omni_sensor'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Omni_Sensor")',
        category = 'hotbuildingExtra', order = 1219,},
    ['tactical_missile_defense'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Tactical_Missile_Defense")',
        category = 'hotbuildingExtra', order = 1220,},
    ['shield_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Shield_Generator")',
        category = 'hotbuildingExtra', order = 1221,},
    ['stealth_field_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Stealth_Field_Generator")',
        category = 'hotbuildingExtra', order = 1222,},
    ['heavy_shield_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Heavy_Shield_Generator")',
        category = 'hotbuildingExtra', order = 1223,},
    ['strategic_missile_defense'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Strategic_Missile_Defense")',
        category = 'hotbuildingExtra', order = 1224,},
    ['wall_section'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Wall_Section")',
        category = 'hotbuildingExtra', order = 1225,},
    ['aeon_quantum_gate_beacon'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Aeon_Quantum_Gate_Beacon")',
        category = 'hotbuildingExtra', order = 1226,},
    ['air_staging'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Air_Staging")',
        category = 'hotbuildingExtra', order = 1227,},
    ['sonar_platform'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Sonar_Platform")',
        category = 'hotbuildingExtra', order = 1228,},
    ['rapid_fire_artillery_installation'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Rapid_Fire_Artillery_Installation")',
        category = 'hotbuildingExtra', order = 1229,},
    ['quantum_optics_facility'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Quantum_Optics_Facility")',
        category = 'hotbuildingExtra', order = 1230,},
    ['engineering_station'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Engineering_Station")',
        category = 'hotbuildingExtra', order = 1231,},
    ['heavy_point_defense'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Heavy_Point_Defense")',
        category = 'hotbuildingExtra', order = 1232,},
    ['torpedo_ambushing_system'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Torpedo_Ambushing_System")',
        category = 'hotbuildingExtra', order = 1233,},
    ['perimeter_monitoring_system'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Perimeter_Monitoring_System")',
        category = 'hotbuildingExtra', order = 1234,},
    ['t2_guided_missile'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Guided_Missile")',
        category = 'hotbuildingExtra', order = 1235,},
    ['t3_shield_disruptor'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Shield_Disruptor")',
        category = 'hotbuildingExtra', order = 1236,},
    ['t2_fighter/bomber'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Fighter/Bomber")',
        category = 'hotbuildingExtra', order = 1237,},
    ['t2_gatling_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Gatling_Bot")',
        category = 'hotbuildingExtra', order = 1238,},
    ['t2_rocket_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Rocket_Bot")',
        category = 'hotbuildingExtra', order = 1239,},
    ['t1_air_scout'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Air_Scout")',
        category = 'hotbuildingExtra', order = 1240,},
    ['t1_interceptor'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Interceptor")',
        category = 'hotbuildingExtra', order = 1241,},
    ['t1_attack_bomber'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Attack_Bomber")',
        category = 'hotbuildingExtra', order = 1242,},
    ['t2_air_transport'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Air_Transport")',
        category = 'hotbuildingExtra', order = 1243,},
    ['t1_light_air_transport'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Light_Air_Transport")',
        category = 'hotbuildingExtra', order = 1244,},
    ['t2_gunship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Gunship")',
        category = 'hotbuildingExtra', order = 1245,},
    ['t2_torpedo_bomber'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Torpedo_Bomber")',
        category = 'hotbuildingExtra', order = 1246,},
    ['t3_spy_plane'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Spy_Plane")',
        category = 'hotbuildingExtra', order = 1247,},
    ['t3_air_superiority_fighter'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Air_Superiority_Fighter")',
        category = 'hotbuildingExtra', order = 1248,},
    ['t3_strategic_bomber'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Strategic_Bomber")',
        category = 'hotbuildingExtra', order = 1249,},
    ['t1_land_scout'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Land_Scout")',
        category = 'hotbuildingExtra', order = 1250,},
    ['t1_mobile_light_artillery'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Mobile_Light_Artillery")',
        category = 'hotbuildingExtra', order = 1251,},
    ['t1_mobile_anti_air_gun'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Mobile_Anti_Air_Gun")',
        category = 'hotbuildingExtra', order = 1252,},
    ['t1_engineer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Engineer")',
        category = 'hotbuildingExtra', order = 1253,},
    ['t1_light_assault_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Light_Assault_Bot")',
        category = 'hotbuildingExtra', order = 1254,},
    ['t2_mobile_missile_launcher'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_Missile_Launcher")',
        category = 'hotbuildingExtra', order = 1255,},
    ['t1_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Tank")',
        category = 'hotbuildingExtra', order = 1256,},
    ['t2_heavy_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Heavy_Tank")',
        category = 'hotbuildingExtra', order = 1257,},
    ['t2_mobile_aa_flak_artillery'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_AA_Flak_Artillery")',
        category = 'hotbuildingExtra', order = 1258,},
    ['t2_engineer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Engineer")',
        category = 'hotbuildingExtra', order = 1259,},
    ['t3_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Tank")',
        category = 'hotbuildingExtra', order = 1260,},
    ['t3_mobile_heavy_artillery'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Mobile_Heavy_Artillery")',
        category = 'hotbuildingExtra', order = 1261,},
    ['t2_mobile_shield_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_Shield_Generator")',
        category = 'hotbuildingExtra', order = 1262,},
    ['t3_engineer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Engineer")',
        category = 'hotbuildingExtra', order = 1263,},
    ['t1_attack_boat'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Attack_Boat")',
        category = 'hotbuildingExtra', order = 1264,},
    ['t1_frigate'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Frigate")',
        category = 'hotbuildingExtra', order = 1265,},
    ['t2_destroyer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Destroyer")',
        category = 'hotbuildingExtra', order = 1266,},
    ['t2_cruiser'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Cruiser")',
        category = 'hotbuildingExtra', order = 1267,},
    ['t1_attack_submarine'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Attack_Submarine")',
        category = 'hotbuildingExtra', order = 1268,},
    ['t3_battleship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Battleship")',
        category = 'hotbuildingExtra', order = 1269,},
    ['t3_aircraft_carrier'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Aircraft_Carrier")',
        category = 'hotbuildingExtra', order = 1270,},
    ['t3_strategic_missile_submarine'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Strategic_Missile_Submarine")',
        category = 'hotbuildingExtra', order = 1271,},
    ['t3_heavy_gunship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Heavy_Gunship")',
        category = 'hotbuildingExtra', order = 1272,},
    ['t2_amphibious_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Amphibious_Tank")',
        category = 'hotbuildingExtra', order = 1273,},
    ['t1_assault_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Assault_Bot")',
        category = 'hotbuildingExtra', order = 1274,},
    ['t3_siege_assault_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Siege_Assault_Bot")',
        category = 'hotbuildingExtra', order = 1275,},
    ['t2_mobile_stealth_field_system'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_Stealth_Field_System")',
        category = 'hotbuildingExtra', order = 1276,},
    ['t2_combat_fighter'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Combat_Fighter")',
        category = 'hotbuildingExtra', order = 1277,},
    ['t3_aa_gunship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_AA_Gunship")',
        category = 'hotbuildingExtra', order = 1278,},
    ['t3_torpedo_bomber'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Torpedo_Bomber")',
        category = 'hotbuildingExtra', order = 1279,},
    ['t2_assault_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Assault_Tank")',
        category = 'hotbuildingExtra', order = 1280,},
    ['t3_sniper_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Sniper_Bot")',
        category = 'hotbuildingExtra', order = 1281,},
    ['t2_submarine_hunter'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Submarine_Hunter")',
        category = 'hotbuildingExtra', order = 1282,},
    ['t3_missile_ship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Missile_Ship")',
        category = 'hotbuildingExtra', order = 1283,},
    ['t3_heavy_air_transport'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Heavy_Air_Transport")',
        category = 'hotbuildingExtra', order = 1284,},
    ['t2_field_engineer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Field_Engineer")',
        category = 'hotbuildingExtra', order = 1285,},
    ['t3_armored_assault_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Armored_Assault_Bot")',
        category = 'hotbuildingExtra', order = 1286,},
    ['t3_mobile_missile_platform'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Mobile_Missile_Platform")',
        category = 'hotbuildingExtra', order = 1287,},
    ['t2_torpedo_boat'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Torpedo_Boat")',
        category = 'hotbuildingExtra', order = 1288,},
    ['t2_shield_boat'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Shield_Boat")',
        category = 'hotbuildingExtra', order = 1289,},
    ['t3_battlecruiser'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Battlecruiser")',
        category = 'hotbuildingExtra', order = 1290,},
    ['t1_light_gunship'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Light_Gunship")',
        category = 'hotbuildingExtra', order = 1291,},
    ['t2_mobile_bomb'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_Bomb")',
        category = 'hotbuildingExtra', order = 1292,},
    ['t2_submarine_killer'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Submarine_Killer")',
        category = 'hotbuildingExtra', order = 1293,},
    ['t2_counter_intelligence_boat'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Counter_Intelligence_Boat")',
        category = 'hotbuildingExtra', order = 1294,},
    ['t1_combat_scout'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T1_Combat_Scout")',
        category = 'hotbuildingExtra', order = 1295,},
    ['t2_assault_bot'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Assault_Bot")',
        category = 'hotbuildingExtra', order = 1296,},
    ['t2_hover_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Hover_Tank")',
        category = 'hotbuildingExtra', order = 1297,},
    ['t2_mobile_anti_air_cannon'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Mobile_Anti_Air_Cannon")',
        category = 'hotbuildingExtra', order = 1298,},
    ['t3_siege_tank'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Siege_Tank")',
        category = 'hotbuildingExtra', order = 1299,},
    ['t3_mobile_shield_generator'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Mobile_Shield_Generator")',
        category = 'hotbuildingExtra', order = 1300,},
    ['t3_submarine_hunter'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Submarine_Hunter")',
        category = 'hotbuildingExtra', order = 1301,},
    ['t3_mobile_aa'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Mobile_AA")',
        category = 'hotbuildingExtra', order = 1302,},
    ['t2_support_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Support_Factory")',
        category = 'hotbuildingExtra', order = 1303,},
    ['t2_support_land_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Support_Land_Factory")',
        category = 'hotbuildingExtra', order = 1304,},
    ['t2_support_air_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Support_Air_Factory")',
        category = 'hotbuildingExtra', order = 1305,},
    ['t2_support_naval_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T2_Support_Naval_Factory")',
        category = 'hotbuildingExtra', order = 1306,},
    ['t3_support_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Support_Factory")',
        category = 'hotbuildingExtra', order = 1307,},
    ['t3_support_land_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Support_Land_Factory")',
        category = 'hotbuildingExtra', order = 1308,},
    ['t3_support_air_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Support_Air_Factory")',
        category = 'hotbuildingExtra', order = 1309,},
    ['t3_support_naval_factory'] = {action= 'UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("T3_Support_Naval_Factory")',
        category = 'hotbuildingExtra', order = 1310,},
}
