-- defines help categories for key actions

keyCategories = {
    ['ui'] = "<LOC keymap_category_0000>UI",
    ['selection'] = "<LOC keymap_category_0004>Selection",
    ['selectionQuickSelect'] = "<LOC keymap_category_0004>Selection - Quick select",
    ['selectionControlGroups'] = "<LOC keymap_selection_control_group>Selection - Control groups",
    ['selectionSubgroups'] = "<LOC keymap_selection_fragments>Selection - Subgroups",
    ['camera'] = "<LOC keymap_category_0025>Camera",
    ['orders'] = "<LOC keymap_category_0036>Orders",
    ['ordersAdvanced'] = "<LOC keymap_orders_queue_based>Orders - Advanced",
    ['ordersQueueBased'] = "<LOC keymap_orders_queue_based>Orders - Queue manipulation",
    ['ordersContextBased'] = "<LOC keymap_orders_context_based>Orders - Mouse context",
    ['game'] = "<LOC keymap_category_0079>Game",
    ['chat'] = "<LOC keymap_category_0087>Chat",
    ['debug'] = "<LOC keymap_category_0088>Debug",
    ['ai'] = "<LOC keymap_ai>Debug - AI tooling",
    ['user'] = "<LOC keymap_category_0090>User",
    ['hotbuilding'] = "<LOC keymap_category_091>Hotbuilding",
    ['hotbuildingAlternative'] = "<LOC keymap_category_093>Alternative Hotbuilding",
    ['hotbuildingExtra'] = "<LOC keymap_category_092>Hotbuilding - Extra keys",
    ['none'] = "<LOC keymap_category_0089>Unassigned Actions",
    ['mods'] = "<LOC keymap_category_0091>Mods",
}

keyCategoryOrder = {
    'orders',
    'ordersAdvanced',
    'ordersQueueBased',
    'ordersContextBased',
    'selection',
    'selectionQuickSelect',
    'selectionControlGroups',
    'selectionSubgroups',
    'hotbuilding',
    'hotbuildingAlternative',
    'hotbuildingExtra',
    'camera',
    'ui',
    'game',
    'chat',
    'user',
    'mods',
    'debug',
    'ai',
    'none'
}
