
--*****************************************************************************
--* File: C:\work\rts\main\data\lua\modules\ui\game\experimetalVO.lua
--* Author: (BOT)Sam Demulling & (BOT)Marshall Macy II
--* Summary: Computer Generated GENERAL VO data for Experimental
--*
--* This file was generated by SCUD.  Do not make manual changes to this file
--* or they will be overwritten!
--*
--* Campaign Faction: none
--* Campaign Description: Generic VO
--* Operation Name: Experimental Unit VO
--* Operation Description: Dialogue used by each faction when constructing Experimental Units
--*
--* Copyright © 2006 Gas Powered Games, Inc.  All rights reserved.
--*****************************************************************************



-- ------------------------------
-- Opnode ID: Aeon
-- Aeon Experimental Unit dialogue
-- ------------------------------

-- \"Galactic Colossus\" Experimental Assault Bot
Experimental_Choir_Aeon_01250 = {text = '<LOC Experimental_Aeon_010_010>[{i Choir}]: The Galactic Colossus uses an energy generator located in its \"eye\" to deliver its deadly payload. When the Colossus is destroyed, its chest opens and an unstable ball of energy is released. It will annihilate anything it touches.', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01250'}
Experimental_Choir_Aeon_01251 = {text = '<LOC Experimental_Aeon_010_020>[{i Choir}]: May the Galactic Colossus eliminate your enemies.', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01251'}
-- \"Tempest\" Submersible Battleship
Experimental_Choir_Aeon_01252 = {text = '<LOC Experimental_Aeon_020_010>[{i Choir}]: A massive battleship, the Tempest is armed with an Oblivion Cannon that hits targets from a great distance. It is supported by an internal Naval Factory, so the Tempest can create naval units as needed.', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01252'}
Experimental_Choir_Aeon_01253 = {text = '<LOC Experimental_Aeon_020_020>[{i Choir}]: The Tempest is now in your hands.', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01253'}
-- \"CZAR\" Flying Fortress
Experimental_Choir_Aeon_01254 = {text = '<LOC Experimental_Aeon_030_010>[{i Choir}]: A massive flying saucer, CZAR unleashes a blistering energy beam that obliterates anything it touches. The CZAR is also able to store air units.', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01254'}
Experimental_Choir_Aeon_01255 = {text = '<LOC Experimental_Aeon_030_020>[{i Choir}]: The CZAR is ready for launch. For the glory of the Aeon!', bank = 'Experimental_VO', cue = 'Experimental_Choir_Aeon_01255'}


-- ------------------------------
-- Opnode ID: Cybran
-- Cybran Experimental Unit dialogue
-- ------------------------------

-- \"Monkeylord\" Spiderbot
Experimental_QAI_Cybran_01233 = {text = '<LOC Experimental_Cybran_010_010>[{i QAI}]: With its heavy Microwave Laser Generator, the \'Monkeylord\' Spiderbot can destroy countless units within seconds. Because of its size, it also crushes any units caught underfoot.', bank = 'Experimental_VO', cue = 'Experimental_QAI_Cybran_01233'}
Experimental_Ops_Cybran_01234 = {text = '<LOC Experimental_Cybran_010_020>[{i Ops}]: Monkeylord ready for battle.', bank = 'Experimental_VO', cue = 'Experimental_Ops_Cybran_01234'}
Experimental_Ops_Cybran_01235 = {text = '<LOC Experimental_Cybran_010_030>[{i Ops}]: Spiderbot is ready to attack.', bank = 'Experimental_VO', cue = 'Experimental_Ops_Cybran_01235'}
-- \"Reaver\" Gunship
Experimental_QAI_Cybran_01236 = {text = '<LOC Experimental_Cybran_020_010>[{i QAI}]: The Reaver is a flying heavy weapons platform. Armed with a Heavy Iridium Rocket Racks and Heavy Electron Bolters, it attacks ground units with crippling force.', bank = 'Experimental_VO', cue = 'Experimental_QAI_Cybran_01236'}
Experimental_Ops_Cybran_01237 = {text = '<LOC Experimental_Cybran_020_020>[{i Ops}]: Your Reaver is ready for field testing, Commander.', bank = 'Experimental_VO', cue = 'Experimental_Ops_Cybran_01237'}
-- \"Scathis\" Mobile Rapid Fire Artillery
Experimental_QAI_Cybran_01240 = {text = '<LOC Experimental_Cybran_030_010>[{i QAI}]: Because of its mobility, the Scathis can unleash a barrage of artillery against nearly any target. Its range is excellent, and its firing speed has been greatly enhanced.', bank = 'Experimental_VO', cue = 'Experimental_QAI_Cybran_01240'}
Experimental_Ops_Cybran_01242 = {text = '<LOC Experimental_Cybran_030_020>[{i Ops}]: Scathis now online.', bank = 'Experimental_VO', cue = 'Experimental_Ops_Cybran_01242'}


-- ------------------------------
-- Opnode ID: UEF
-- UEF Experimental Unit dialogue
-- ------------------------------

-- \"Fatboy\" Mobile Factory
Experimental_EarthCom_UEF_01219 = {text = '<LOC Experimental_UEF_010_010>[{i EarthCom}]: The Fatboy is a land-based battleship. Tri-barreled cannons positioned along its perimeter can unleash a devastating artillery barrage, and the rear construction bay offers excellent reinforcement capabilities.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01219'}
Experimental_EarthCom_UEF_01220 = {text = '<LOC Experimental_UEF_010_020>[{i EarthCom}]: The Fatboy has completed construction.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01220'}
-- \"Atlantis\" Submersible Aircraft Carrier
Experimental_EarthCom_UEF_01223 = {text = '<LOC Experimental_UEF_020_010>[{i EarthCom}]: The Atlantis Aircraft Carrier is the premier air projection component in the EarthCom navy. It stores air units and comes standard with light anti-air support and torpedo tubes.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01223'}
Experimental_EarthCom_UEF_01224 = {text = '<LOC Experimental_UEF_020_020>[{i EarthCom}]: The Atlantis is ready for deployment.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01224'}
-- \"Mavor\" Long Range Strategic Artillery
Experimental_EarthCom_UEF_01228 = {text = '<LOC Experimental_UEF_030_010>[{i EarthCom}]: The Mavor\'s firing chamber has been modified to fire tactical nuclear shells extremely long distances. Its range is unsurpassed by any known weapon.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01228'}
Experimental_EarthCom_UEF_01230 = {text = '<LOC Experimental_UEF_030_020>[{i EarthCom}]: The Mavor is now operational.', bank = 'Experimental_VO', cue = 'Experimental_EarthCom_UEF_01230'}

