
-------------------------------------------------------------------------------
-- Summary: Contains all builder conditions that directly interface with
-- the structure manager
--
-- All builder conditions in this file are of complexity O(1)
-------------------------------------------------------------------------------

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function LessStructuresByTech(aiBrain, base, count, tech)
    if base.StructureManager.Structures[tech] < count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function MoreStructuresByTech(aiBrain, base, count, tech)
    if base.StructureManager.Structures[tech] > count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function LessStructuresBeingbuiltByTech(aiBrain, base, count, tech)
    if base.StructureManager.StructureBeingBuiltCount[tech] < count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function MoreStructuresBeingbuiltByTech(aiBrain, base, count, tech)
    if base.StructureManager.StructureBeingBuiltCount[tech] > count then
        return true
    end

    return false
end

--- Returns true when the surface threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreSurfaceThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Surface > amount
end

--- Returns true when the sub threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreSubThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Sub > amount
end

--- Returns true when the air threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreAirThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Air > amount
end

--- Returns true when the economy threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreEconomyThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Economy > amount
end

--- Returns true when the surface threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessSurfaceThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Surface < amount
end

--- Returns true when the sub threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessSubThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Sub < amount
end

--- Returns true when the air threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessAirThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Air < amount
end

--- Returns true when the economy threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessEconomyThreatThan (aiBrain, base, amount)
    return base.StructureManager.GeneratedThreat.Economy < amount
end
