--******************************************************************************************************
--** Copyright (c) 2022  Willem 'Jip' Wijnia
--**
--** Permission is hereby granted, free of charge, to any person obtaining a copy
--** of this software and associated documentation files (the "Software"), to deal
--** in the Software without restriction, including without limitation the rights
--** to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
--** copies of the Software, and to permit persons to whom the Software is
--** furnished to do so, subject to the following conditions:
--**
--** The above copyright notice and this permission notice shall be included in all
--** copies or substantial portions of the Software.
--**
--** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
--** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
--** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
--** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
--** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
--** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
--** SOFTWARE.
--******************************************************************************************************

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function LessStructuresByTech(aiBrain, base, platoon, count, tech)
    if base.StructureManager.Structures[tech] < count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function MoreStructuresByTech(aiBrain, base, platoon, count, tech)
    if base.StructureManager.Structures[tech] > count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function LessStructuresBeingbuiltByTech(aiBrain, base, platoon, count, tech)
    if base.StructureManager.StructureBeingBuiltCount[tech] < count then
        return true
    end

    return false
end

---@param aiBrain AIBrain
---@param base AIBase
---@param count number
---@param tech TechCategory
---@return boolean
function MoreStructuresBeingbuiltByTech(aiBrain, base, platoon, count, tech)
    if base.StructureManager.StructureBeingBuiltCount[tech] > count then
        return true
    end

    return false
end

--- Returns true when the surface threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreSurfaceThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Surface > amount
end

--- Returns true when the sub threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreSubThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Sub > amount
end

--- Returns true when the air threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreAirThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Air > amount
end

--- Returns true when the economy threat generated by the structures of this base is more than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function MoreEconomyThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Economy > amount
end

--- Returns true when the surface threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessSurfaceThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Surface < amount
end

--- Returns true when the sub threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessSubThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Sub < amount
end

--- Returns true when the air threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessAirThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Air < amount
end

--- Returns true when the economy threat generated by the structures of this base is less than the amount
---@param aiBrain AIBrain
---@param base AIBase
---@param amount number
---@return boolean
function LessEconomyThreatThan (aiBrain, base, platoon, amount)
    return base.StructureManager.GeneratedThreat.Economy < amount
end
