--****************************************************************************
--**  File     :  /lua/sim/MarkerGenerator.lua
--**  Authored by (Jip) Willem Wijnia - shared under the GPL V3 license
--****************************************************************************
