--*****************************************************************************
--* File: lua/modules/ui/lobby/ainames.lua
--* Author: Chris Blackwell
--* Summary: Contains a list of names the AI can assign to units
--*
--* Copyright © 2006 Gas Powered Games, Inc.  All rights reserved.
--*****************************************************************************

ainames = {
    uef = {
        "Harms",
        "Gibson",
        "Keville",
        "St. Croix",
        "Jables",
        "Janicki",
        "Stackhouse",
        "Staltman",
        "Kirwan",
        "Daniels",
        "Defwode",
        "Blackwell",
        "Cox",
        "Budac",
        "Rebh",
        "Garat",
        "Rumsey",
        "Williamson",
        "Smolko",

        "Johanson",
        "DeMelt",
        "Steenis",
        "Oates",
        "Tengelin",
        "Devon",
        "Bingham",
        "Tomandl",
        "Cleveland",
        "Murdock",
        "Xavier",
        "Mavor",
        "Vasudevan",
        "Vidhee",
        "Dimmick",
        "Lundquist",
        "Zimm",
        "Shinjake",
        "Porter",
        "Kohne",
        "Carlos",
        "Lacerna",
    },
    aeon = {
        "Priscilla",
        "Maddie",
        "Tedles",
        "Chloe",
        "Zoe",
        "Jessica",
        "Jacqueline",
        "Shuri",
        "Dru",
        "Gerard",
        "Nevyin",
        "Christopher",
        "Keiko",
        "Ania",
        "Audrey",
        "June",
        "Ivan",
        "Emily",
        "Maegan",
        "Simone",
        "Juliet",
        "Albarel",
        "Jagels",

        "Daroza",
        "Logan",
        "Trudi",
        "Pheobe",
        "Yare",
        "Lanette",
        "Sletir",
        "Maggie",
        "Ranga",
        "Motoko",
        "Bassima",
        "Wizzim",
        "Jalbert",
        "Janus",
        "Isus",
        "Ocarina",
        "Angel",
        "Kayleen",
        "Xinellum",
        "Lish",
        "Mazpar",
        "Judith",
        "Alexandra",
        "Jaime",
        "Julian",
        "La'Marr",
    },
    cybran = {
        "Ronald",
        "Mendez",
        "BatGecko",
        "Snooker",
        "CR07-A",
        "M4h0n",
        "Kraglor",
        "Fu Hok",
        "Hawthorne",
        "DFS",
        "Winter Knight",
        "Spyder",
        "Daedalus",
        "Squid",
        "Kijanka",
        "Phoenix",
        "Flounder",
        "Yo-Yo",
        "Cain",
        "Xahvres",
        "Patatron",
        "Damian",

        "XShadowStormX",
        "Cracker",
        "Blacklisted",
        "Avatar",
        "Sleepy",
        "Creamy",
        "Smooth",
        "Wyxe",
        "MCS500",
        "Foe Hammer",
        "5Iron",
        "TheContact",
        "Jackal",
        "C@tch22",
        "Rokion Era",
        "Unfather",
        "TargetDrone",
        "Rodan",
        "GStar",
        "Sckricko",
        "Fernando",
        "El Guapo",
        "Tyo",
        "Istvan",
    },
    seraphim = {
        "Ahn-Ullevash",
        "Ahn-Aishayeth",
        "Ahn-Iashen",
        "Ahn-Ushithow",
        "Shun-Awloyeth",
        "Shun-Ushi",
        "Shun-Ylliushi",
        "Shun-Eoshi",
        "Zan-Iavow",
        "Zan-Ilnaa",
        "Zan-Uyalthow",
        "Zan-Uushen",
        "Oum-Ullehesh",
        "Oum-Uyal",
        "Oum-Ashavoh",
        "Oum-Uthinaa",
        "Thel-Aishashen",
        "Thel-Awloshi",
        "Thel-Ylliuhesh",
        "Thel-Ilthow",
        "Seth-Eovash",
        "Seth-Uu",
        "Seth-Ushavoh",
        "Seth-Uthivow",

        "Paj-Tshiab",
        "Al-Ghoussein",
    },
}
