last_version = 3660
changelog = {
    {
        version = 3,
        name = "Lobby 2.5 (3636 patch)",
        description = {
            "- Add Changelog dialog",
            "- Add numbers of Restriction in OptionContainer",
            "- Add new view in ModManager",
            "- Add 'Show system message' option for see (connecting players, go observers, disconnected, ...)",
            "- Add 'Player Swapped' message",
            "- Add 'Connected with xxx (with FAF Proxy)' message see if is connected with FAFproxy",
            "- Add 1250 and 1500 Units Caps",
            "- Add Windowed options for launch Lobby windowed until launch [by Crotalus]",
            "- Add Autobalance the teams when spawn is random [by Crotalus]",
            "- Add new restrictions (NoEngineeringStation+EnhancementDrone), (NoEyeofRhianneandSoothsayer)",
            "- Add translation for Unit Restrictions and re-order [by Xinnony, Navax's,  aeoncleanse]",
            "- Fix the Mod UI not activated directly [by Crotalus]",
            "- Fix Preset not loaded correctly (exemple FinalRushPro, but need recreate preset)",
            "- Fix ModManager crash sometime",
            "- Fix a bug in Game Options, the new value is reset if you scroll the list",
            "- Fix sometime a PresetLobby not loaded (caused by map not available)",
            "- Fix 'CH' and 'VA' and yellow Flag Country",
            "- Replace Checkbox to Radiobox in ModManager",
            "- Replace the 'world' flag country",
            "- Delete 'Player go to Slot' message",
            "- Delete 'Player go to Observer' message",
            "- Remember a options 'Hide default Options'",
            "- Show message if map is not available in PresetLobby",
            "- SpeedUp UpdateGame(), merge 3 loops",
            "- Typo in 'Lobby options'",
            "- The ConnectDialog lasts until the lobby is fully loaded",
            "- Typo 'x mods UI' to 'x UI mods' (KRAMP idea)",
            "- Now you can see and select only the color available",
            "- Transparent color the ACU in Minimap (just the grey color, not the black border)",
            "- Typos in PresetLobby",
        }
    },
    {
        version = 4,
        name = "Lobby 2.5b",
        description = {
            "- Disable Windowed options if the game is already set windowed",
            "- Add color for the default options in Game Options window",
            "- Add Tooltip for the Mod in Mod Manager with Little View",
            "- Fix people can change color of other people",
            "- Fix wrong description for Eye and Soothsayer Unit Restrictions",
            "- Fix people can't join/host (black screen lobby)",
            "- Fix problem with Preset Lobby",
            "- Remove debug message",
        }
    },
    {
        version = 6,
        name = "Lobby 2.6.0",
        description = {
            "- Fix the rating not showing up for observers",
            "- Font-size for observers reduced",
            "- Chat font-size adjustable from options",
            "- Remove debug messages",
            "- Connection dialog no longer appears below lobby slots",
            "- Fixed issue with players not being removed from slots on disconnect",
            "- Fix integrated replaysync",
            "- Clan tags are shown in game",
            "- 'Set ranked options' button works again",
            "- Tooltips for various buttons fixed and text revised",
            "- More detailed large map preview",
            "- Seraphim icons normalized",
            "- Both players get ready flag cleared on swap",
            "- Removed extra space around Rerun CPU benchmark button",
            "- Made 'Random faction' skin load the chosen faction skin (Before it would always be UEF)",
            "- Fixed a problem preventing player colours from being updated correctly",
            "- Prevented CPU benchmark from running once the game starts",
            "- General performance improvements"
        }
    },
    {
        version = 7,
        name = "Lobby 2.7.0",
        description = {
            "- Lots of bug fixes",
            "- Lots of UI polish",
            "- Resources are now shown in all map previews",
            "- The unit manager can once again be seen by non-host players",
            "- Preset system now saves activated mods",
            "- Observers can now open the chat menu by pushing ENTER",
            "- Further performance improvements",
            "- Team selectors disabled when auto-teams is overriding them",
            "- Fixed issue with idle engineer lists",
            "- Clan tags are now shown in lobby"
        }
    },
    {
        version = 3660,
        name = "Game Version 3660",
        description = {
            "**Lobby**",
            "",
            "- Fixed team number switching slots alongside a player",
            "- Added new feature: Kick Reasons. When kicking a player from your lobby, you get a new dialog. You may type in a reason for the kick to notify the player. If you blank it, or leave the message as ",
            "      presented, it will play the old message.",
            "- Fixed Cheat and Build multipliers for AIs showing 1.0 - 1.9 two times",
            "- Fixed rating labels being shown on the minimap when teams are not set to 'Fixed'",
            "- Made it clearer that there's a search filter in the map selection",
            "- Added new unit share conditions for interesting new gameplay. 'Full Share' and 'Share Until Death' have been joined by 'Traitors', which gifts all your units to the player who killed you ",
            "      (Very interesting for FFA games), 'Defectors', which is the opposite of Full Share, gifting your units to the highest scoring enemy, and 'Civilian Desertion', which gifts your units to a neutral ",
            "      civilian AI, if there is one.",
            "- Improved the tooltip when hovering over your score in the lobby. It will now show a more detailed explanation including your rating deviation",
            "- Fixed the position of the load button in Skirmish mode when launching offline",
            "- Fixed 'Odd vs Even' autoteam button for random faction being the same as the 'Top vs Bottom'", 
            "- Fixed new players joining a lobby being unable to see closed slots as being closed",
            "- Fixed auto team settings not working for games with >8 players",
            "- Changed 'Remove Player' to 'Kick Player' for clarity",
            "",
            "**Coop**",
            "- Fixed cinematics playing in coop games",
            "- Improved AI sACU usage",
            "- Fixed objective protection timer",
            "- Fixed information sent to the server for leaderboard purposes",
            "",
            "**Gameplay**",
            "- Improved Selen toggle. It now behaves with no abilities by default, then when toggled on it hides and shows based on motion as before",
            "- Added dummy weapon to Aeon T2 Transport to allow LABs to be targeted to specific enemies",
            "- Allowed UEF T2 Transport to be given targets while landed on water",
            "- Enabled templates to be created with modded units as the primary unit",
            "- New feature: Delayed Unit Transfer. Hold shift while giving a unit to another player to have it transfer once it finishes the command queue. Partiicularly useful when used with transports",
            "- New feature: You can now cap mass extractors with storage by right-clicking a T2 or T3 mex, or double-shift-right-clicking an upgrading T1 or T2 mex, with an Engineer",
            "- New feature: All ACUs now begin the game pointed towards the centre of the map, making things fairer between north and south on most maps",
            "- Greatly improved teleport visuals for all ACUs and sACUs. Some of these effects are only used in coop",
            "- T2 Artillery should more rarely shoot the floor in front of themselves in odd terrain situations",
            "- Fixed Mermaid being unable to be hit by Neptune and Seraphim Destroyer fire",
            "- Share Until Death now kills your walls as well. All other modes leave them intact",
            "",
            "**Bugs**",
            "- Fixed units carried by UEF T2 Gunship from firing from inside a carrier",
            "- Fixed Salvation fire rate slowing at max adjacency instead of speeding up",
            "- Fixed units being able to fire at aircraft docked inside carriers, damaging the carrier",
            "- Fixed games not ending properly with AIs",
            "- Fixed Continental not dying to nukes (Again)",
            "- Fixed upgraded structures not being targetable via radar blip",
            "- Fixed shared unit cap taking civilian armies into account when sharing on player death",
            "- Fixed UEF sACU AOE upgrade removal reducing the AOE too far",
            "- Fixed the Spiderbot's laser beam getting stuck on temporarily while the unit executed the death animation",
            "- Fixed the Cybran ACU wandering off long distance when told to assist various buildings with an enemy in the rough vicinity. It will still happen if the unit is much closer, but we should no longer ",
            "      have ACUs walking across the map to go kill themselves on enemy PD",
            "- Fixed Seraphim ACU weapon trail showing when zoomed out",
            "- Fixed Neptune Class weapon getting stuck on during death sequence",
            "- Fixed a large number of projectiles showing the trails through fog of war",
            "- Fixed T3 Mobile Artillery not quite being able to fire to the edge of their radius in some circumstances",
            "- Fixed Siren ground toggle weapon using air weapon target priorities",
            "- Fixed an error in timer resolution in coop mode",
            "",
            "**UI**",
            "- Fixed UEF Engineering station strategic icon not matching the tech level",
            "- Added missing strategic build icons used in 'Bigger' mode",
            "- Fixed displayed abilities on several units",
            "- Fixed unit descriptions on support factories displaying for the wrong ones",
            "- Fixed game quality displaying a corrupted string",
            "- Fixed the scroll button in ACU enhancements freezing the tooltip popup action",
            "- Added mod icon support for various UI elements",
            "- Added build mode support for SCU presets",
            "- Fixed a large number of tooltips not having proper localization",
            "- Added some tooltips to features previously missing them",
            "- Added ability to toggle reclaim labels. Set to Alt-R by default. You may have to bind this manually in the F1 menu.",
            "- Massively improved reclaim label implementation to remove lag when zooming or panning",
            "- Fixed a bug which caused the menu to block the top-left of the screen in ladder games",
            "",
            "**Other**",
            "- Removed obsolete strategic icons and corrected file paths inside Hotstats module",
            "- Fixed custom FAF player colours conflicting with Steam launcher",
            "- Added German translation to FAF",
            "",
            "**Contributors**",
            "- Crotalus",
            "- Exotic-Retard",
            "- IceDreamer",
            "- Ithilis",
            "- Justify87",
            "- SlinkingAnt",
            "- Speed2",
            "- Uveso",
        }
    }
}
