--Tips showed on the loading screen
Tips = {
    "<LOC loadingtip_0001>At least one Energy Storage and 5000 energy is required to fire ACU’s Overcharge cannon",
    "<LOC loadingtip_0002>Always build Energy Storage in a place where it won’t kill anything if it dies",
    "<LOC loadingtip_0003>Overcharge deals 400 damage to ACUs and 800 damage to buildings",
    "<LOC loadingtip_0004>Don't build Mass Fabricators unless you have upgraded every available T2 Mass Extractor to T3",
    "<LOC loadingtip_0005>Build Mass Storages around all T2 Mass Extractors before upgrading them to T3",
    "<LOC loadingtip_0006>Upgrade a Mass Extractor to T2 before you build Mass Storages around it",
    "<LOC loadingtip_0007>ACUs in the water are harder to spot and snipe, use this especially in the lategame",
    "<LOC loadingtip_0008>Nuke silos take 5 minutes to build a missile un-assisted, Anti-Nukes take 4 minutes",
    "<LOC loadingtip_0009>You can use attack move from factory to increase engineers’ reclaim range",
    "<LOC loadingtip_0010>Use attack move with engineers in order to reclaim",
    "<LOC loadingtip_0011>Loyalists can deflect tactical missiles",
    "<LOC loadingtip_0012>The Monkeylord is the cheapest land experimental unit",
    "<LOC loadingtip_0013>Start building a second Paragon as soon as you finish your first one",
    "<LOC loadingtip_0014>Place a move order before building a structure to make use of the build range",
    "<LOC loadingtip_0015>The Seraphim destroyer is the only destroyer that can be submerged",
    "<LOC loadingtip_0016>Tech 1 Mass Extractors only need a few seconds to pay back their investment",
    "<LOC loadingtip_0017>Rebuilding structures on their wrecks saves you 50% of construction cost and time",
    "<LOC loadingtip_0018>An un-upgraded ACU is equivalent to 20 T1 tanks and 2 T1 Engineers",
    "<LOC loadingtip_0019>Always build Tactical Missile Defense as soon as you have T2",
    "<LOC loadingtip_0020>Hydrocarbon generator has the same power outcome as 5 T1 Power Generators but it’s much cheaper",
    "<LOC loadingtip_0021>Aeon T3 Mobile Artillery can shoot while it’s moving",
    "<LOC loadingtip_0022>Include reclaiming rocks around your start position into your build order",
    "<LOC loadingtip_0023>The small yellow ring around the ACU and Engineers shows their build range",
    "<LOC loadingtip_0024>Aeon ACU with both gun upgrades has a larger range compared to the other ACUs",
    "<LOC loadingtip_0025>Reclaiming Power Generators when they are about to die won’t trigger the explosion",
    "<LOC loadingtip_0026>AYou need 2500HP on your ACU to survive another ACU’s explosion",
    "<LOC loadingtip_0027>Always build Walls around your T1 Point Defences",
    "<LOC loadingtip_0028>Build your own Air Scouts, don’t rely on anyone else",
    "<LOC loadingtip_0029>Orders can be cancelled by Ctrl+Shift+Right Click",
    "<LOC loadingtip_0030>Units on Attack Move will stop and attack units in their weapon range",
    "<LOC loadingtip_0031>Patrol and Attack Move have the same functionality, but Patrol is endless",
    "<LOC loadingtip_0032>Use T1 Mobile Artillery to kill T1 Point Defenses",
    "<LOC loadingtip_0033>Power Generators adjacent to Static Artilleries will increase their rate of fire",
    "<LOC loadingtip_0034>Engineers are more efficient for build power than Engineering Stations",
    "<LOC loadingtip_0035>Overcharge can deal up to 15 000 damage to an unit, depending on your energy stock",
}

