--Tips showed on the loading screen
Tips = {
    "<LOC loadingtip_0001>At least 7500 energy is required to fire the ACU’s Overcharge cannon",
    "<LOC loadingtip_0002>You should build Energy Storage in a place where it won’t damage anything if it gets destroyed",
    "<LOC loadingtip_0003>Overcharge deals 400 damage to ACUs and 800 damage to buildings",
    "<LOC loadingtip_0004>Don’t build Mass Fabricators unless you have upgraded every available T2 Mass Extractor to T3",
    "<LOC loadingtip_0005>Build Mass Storages around all T2 Mass Extractors before upgrading them to T3",
    "<LOC loadingtip_0006>Upgrade a Mass Extractor to T2 before you build Mass Storages around it",
    "<LOC loadingtip_0007>ACUs in the water are harder to spot and snipe—use this, especially late in the match",
    "<LOC loadingtip_0008>Strategic missiles take 5 minutes to build, but defensive missiles only take 4",
    "<LOC loadingtip_0009>You can use Attack-Move from factories to increase Engineers’ reclaim range",
    "<LOC loadingtip_0010>You can use Attack-Move with Engineers in order to reclaim",
    "<LOC loadingtip_0011>Loyalists can deflect tactical missiles",
    "<LOC loadingtip_0012>The Monkeylord Experimental Spiderbot is the cheapest experimental unit",
    "<LOC loadingtip_0013>Consider building a second Paragon as soon as you finish your first one",
    "<LOC loadingtip_0014>Place a Move order close-by before building a structure to make better use of build range",
    "<LOC loadingtip_0015>The Uashavoh Seraphim Destroyer is the only destroyer that can be submerged",
    "<LOC loadingtip_0016>T1 Mass Extractors only need a few seconds to pay back their investment",
    "<LOC loadingtip_0017>Rebuilding structures on their wrecks saves you 50% of the construction cost and time",
    "<LOC loadingtip_0018>An un-upgraded ACU is equivalent to 20 T1 tanks and 2 T1 Engineers",
    "<LOC loadingtip_0019>You should build Tactical Missile Defense soon after you have reached T2",
    "<LOC loadingtip_0020>A Hydrocarbon Powerplant has the same power output as 5 T1 Power Generators, but it’s much cheaper",
    "<LOC loadingtip_0021>The Serenity Mobile Heavy Artillery can shoot while it moves",
    "<LOC loadingtip_0022>Include reclaiming rocks around your start position into your build order",
    "<LOC loadingtip_0023>The small yellow ring around the ACU and Engineers shows their build range",
    "<LOC loadingtip_0024>An Aeon ACU with the Enhanced Quantum Disruptor upgrade has a larger range than the other upgraded ACUs do",
    "<LOC loadingtip_0025>Reclaiming volatile buildings when they are about to be destroyed prevents them from exploding",
    "<LOC loadingtip_0026>You need 2500 health on your ACU to survive another ACU explosion",
    "<LOC loadingtip_0027>Protect your T1 Point Defenses by surrounding them with walls",
    "<LOC loadingtip_0028>Build your own Air Scouts; don’t rely on anyone else",
    "<LOC loadingtip_0029>Orders and Markers can be deleted by {i properkeyname_0010}+{i properkeyname_0009}+Right Clicking them",
    "<LOC loadingtip_0030>Combat units on Attack-Move will stop to follow and attack enemy units in their weapon range",
    "<LOC loadingtip_0031>The Patrol and Attack-Move orders function somewhat similarly, but Patrol is endless",
    "<LOC loadingtip_0032>T1 Mobile Artillery out-ranges T1 Point Defense",
    "<LOC loadingtip_0033>Putting Power Generators adjacent to static artilleries will increase their rate of fire",
    "<LOC loadingtip_0034>Engineers are more mass-efficient for build power than Engineering Stations are, but they can have pathing issues",
    "<LOC loadingtip_0035>Dealing maximum damage with overcharge (15,000) costs 90k energy and requires at least 100k energy in your storage",
    "<LOC loadingtip_0036>The Salem Class Destroyer cannot shoot backwards",
    "<LOC loadingtip_0037>The Salem Class Destroyer has a toggle ability that lets it walk on land",
    "<LOC loadingtip_0038>Generally, only build a Salvation after you have built a Paragon",
    "<LOC loadingtip_0039>Engineers on an Attack-Move or Patrol order will stop reclaiming when your storage is nearly full",
    "<LOC loadingtip_0040>Stealth only hides units from radar, Cloaking only from vision—Omni sees through both",
    "<LOC loadingtip_0041>Veterancy is based on the mass value of the destroyed unit and what percentage of the damage each unit contributed",
    "<LOC loadingtip_0042>To destroy a unit with a single overcharge, you need 1 Energy Storage for T1 units, up to 2 for T2, and up to 6 for T3",
    "<LOC loadingtip_0043>To see stealthed underwater units you need water vision or Omni",
    "<LOC loadingtip_0044>Always keep building available Mass Extractors throughout the map",
    "<LOC loadingtip_0045>Use combat units to take mass deposits, take map control, and counter the enemy",
    "<LOC loadingtip_0046>Use your ACU to secure mass deposit groups and engage in combat early in the match",
    "<LOC loadingtip_0048>Keep scouting throughout the game; having intelligence on the enemy can be key to victory",
    "<LOC loadingtip_0049>Pay attention to what you scout while you have vision on the enemy’s base",
    "<LOC loadingtip_0051>Taking the right battles and avoiding the wrong ones becomes especially important in air fights",
    "<LOC loadingtip_0052>Don’t play too zoomed in—there are more important things than perfect adjacency and base layout!",
    "<LOC loadingtip_0053>Macro-management is almost always more important than micro-management",
    "<LOC loadingtip_0055>Generally try to avoid having idle units without a good reason, especially early in the match",
    "<LOC loadingtip_0056>Setting up good hotkeys can help you save time—press {k toggle_key_bindings} in-game and try out a key preset",
    "<LOC loadingtip_0057>Focus on doing the best you can and learning what you can do better instead of blaming others",
    "<LOC loadingtip_0058>With enough scouting, you can know what the enemy is up to and counter their strategy",
    "<LOC loadingtip_0059>Bombers are highly effective against armies with minimal Anti-Air and no air support",
    "<LOC loadingtip_0060>If the enemy uses lots of static defenses, you can often go around them, out-range them, or ignore them and build up your economy",
    "<LOC loadingtip_0061>If the enemy uses lots of T1 or T2 aircraft, you can make interceptors and T2 mobile flak",
    "<LOC loadingtip_0062>If the enemy’s economy is a lot larger than yours, they may not have enough units to defend it",
    "<LOC loadingtip_0063>If the enemy hunkers down without controlling much of the map, they may not have the economy to win later",
    "<LOC loadingtip_0064>If the enemy is acting aggressively, you can try to bait them into battles that are better for you",
    "<LOC loadingtip_0067>Manually reclaiming can be useful during very early in the match when you have nothing better to do",
    "<LOC loadingtip_0068>Attack-Move orders are preferable to Patrol orders in most situations so that you know when the orders are completed",
    "<LOC loadingtip_0070>Fight battles in spots where you can easily reclaim the wreckage and the enemy cannot",
    "<LOC loadingtip_0071>Wreckage can yield up to 81% of a unit’s mass cost, depending on unit tier",
    "<LOC loadingtip_0072>It can be worthwhile to reclaim your old low-tech units or badly damaged high-tech ones to get additional mass",
    "<LOC loadingtip_0073>Think about value and opportunity costs (e.g. would you rather have ~16 T1 tanks or 1 T2 Mass Extractor?)",
    "<LOC loadingtip_0074>Low-tech units often do more damage per cost, but have less health per cost compared to higher-tech units",
    "<LOC loadingtip_0075>Upgrading a factory costs resources that could have been put into units, so don’t upgrade too early",
    "<LOC loadingtip_0077>Let your team know if you need help",
    "<LOC loadingtip_0078>Ask your team for advice if you don’t know what to do",
    "<LOC loadingtip_0079>If you have extra mass and can’t spend it fast enough, you can gift it to a teammate who can",
    "<LOC loadingtip_0081>Ping or mark enemy threats your team hasn’t noticed yet",
    "<LOC loadingtip_0082>Coordinating maneuvers with your teammates is more effective than acting separately",
    "<LOC loadingtip_0083>Having a positive attitude can help you to play better, learn more, and have more fun",
    "<LOC loadingtip_0084>You can learn a lot from analyzing replays",
    "<LOC loadingtip_0085>Remember to have fun—winning can be enjoyable, but it isn’t everything!",
    "<LOC loadingtip_0087>You can ask for gameplay advice and replay reviews on the FAF Discord",
    "<LOC loadingtip_0088>The FAF wiki has useful guides that can teach you how to get better at Supreme Commander",
    "<LOC loadingtip_0089>Scale your economy (mass income, energy income, and build power) over time",
    "<LOC loadingtip_0090>Mass-producing lower-tech units is often very effective, but don’t forget to transition to higher-tech units",
    "<LOC loadingtip_0091>Non-Aeon T2 Fighter/Bombers are not efficient to control the air—use T1 Interceptors until you get T3 Air Superiority Fighters",
    "<LOC loadingtip_0092>Avoid stalling on energy—units and structures that have a power maintenance will begin to lose their benefits when you do so",
    "<LOC loadingtip_0093>It’s better to spend mass than to let it sit in storage",
    "<LOC loadingtip_0094>Avoid building too many Power Generators—they cost resources that can be spent on more useful units",
    "<LOC loadingtip_0095>If you are stalling on mass, it might be a good idea to have more of your engineers reclaiming",
    "<LOC loadingtip_0096>It’s generally a good idea to expand around the map early on to get mass deposits, reclaim, and map control",
    "<LOC loadingtip_0097>If all players agree to a draw, you can end a slow or unfair match with a tie",
    "<LOC loadingtip_0098>If you can’t spend your resources, you may not have enough build power (Engineers, Factories, Engineering Stations, or SACUs)",
    "<LOC loadingtip_0099>If you don’t think your team can win anymore, you can request them to Recall from battle while you continue to fight for them",
    "<LOC loadingtip_0100>You can find other players to team up with or talk about Forged Alliance Forever on the FAF Discord",
}
