--Tips showed on the loading screen
Tips = {
    "<LOC loadingtip_0001>At least 5000 energy is required to fire the ACU's Overcharge",
    "<LOC loadingtip_0002>You should build Energy Storage in a place where it won't kill anything if it dies",
    "<LOC loadingtip_0003>Overcharge deals 400 damage to ACUs and 800 damage to buildings",
    "<LOC loadingtip_0004>Don't build Mass Fabricators unless you have upgraded every available T2 Mass Extractor to T3",
    "<LOC loadingtip_0005>Build Mass Storages around all T2 Mass Extractors before upgrading them to T3",
    "<LOC loadingtip_0006>Upgrade a Mass Extractor to T2 before you build Mass Storages around it",
    "<LOC loadingtip_0007>ACUs in the water are harder to spot and snipe - use this, especially in the late game",
    "<LOC loadingtip_0008>Nuclear missiles take 5 minutes to build, but defensive missiles only take 4",
    "<LOC loadingtip_0009>You can use Attack-Move from factory to increase Engineers' reclaim range",
    "<LOC loadingtip_0010>You can use Attack-Move with Engineers in order to reclaim",
    "<LOC loadingtip_0011>Loyalists can deflect tactical missiles",
    "<LOC loadingtip_0012>The Monkeylord is the cheapest land experimental unit",
    "<LOC loadingtip_0013>Start building a second Paragon as soon as you finish your first one",
    "<LOC loadingtip_0014>Place a move order close by before building a structure to make use of the build range",
    "<LOC loadingtip_0015>The Seraphim destroyer is the only destroyer that can be submerged",
    "<LOC loadingtip_0016>Tech 1 Mass Extractors only need a few seconds to pay back their investment",
    "<LOC loadingtip_0017>Rebuilding structures on their wrecks saves you 50% of the construction cost and time",
    "<LOC loadingtip_0018>An un-upgraded ACU is equivalent to 20 T1 tanks and 2 T1 Engineers",
    "<LOC loadingtip_0019>You should build Tactical Missile Defense soon after you have reached T2",
    "<LOC loadingtip_0020>A hydrocarbon generator has the same power outcome as 5 T1 Power Generators, but it's much cheaper",
    "<LOC loadingtip_0021>Aeon T3 Mobile Artillery can shoot while it's moving",
    "<LOC loadingtip_0022>Include reclaiming rocks around your start position into your build order",
    "<LOC loadingtip_0023>The small yellow ring around the ACU and Engineers shows their build range",
    "<LOC loadingtip_0024>An Aeon ACU with the Enhanced Quantum Disruptor upgrade has a larger range than the other ACUs",
    "<LOC loadingtip_0025>Reclaiming volatile buildings when they are about to die prevents triggering the explosion",
    "<LOC loadingtip_0026>You need 2500HP on your ACU to survive another ACU's explosion",
    "<LOC loadingtip_0027>Protect your T1 Point Defences with walls around it",
    "<LOC loadingtip_0028>Build your own Air Scouts; don't rely on anyone else",
    "<LOC loadingtip_0029>Orders can be cancelled by Ctrl+Shift+Right Click",
    "<LOC loadingtip_0030>Units on Attack-Move will stop and attack units in their weapon range",
    "<LOC loadingtip_0031>Patrol and Attack-Move have the same functionality, but Patrol is endless",
    "<LOC loadingtip_0032>Use T1 Mobile Artillery to kill T1 Point Defenses",
    "<LOC loadingtip_0033>Power Generators adjacent to Static Artilleries will increase their rate of fire",
    "<LOC loadingtip_0034>Engineers are more efficient for build power than Engineering Stations",
    "<LOC loadingtip_0035>Dealing maximum damage with overcharge (15,000), costs 60k energy and requires at least 67k energy in your storage",
    "<LOC loadingtip_0036>The Salem cannot shoot backwards",
    "<LOC loadingtip_0037>Toggle the Salem's ability to let it also move on land",
    "<LOC loadingtip_0038>Only build a Salvation after you have built a Paragon",
    "<LOC loadingtip_0039>Your Engineers on Patrol or Attack-Move order will stop reclaiming when your storage is nearly full",
    "<LOC loadingtip_0040>Stealth only hides units from radar, cloak only from vision",
    "<LOC loadingtip_0041>Veterancy is based on the mass value of the killed unit and how much damage a unit dealt to it",
    "<LOC loadingtip_0042>To kill with a single overcharge, you need 1 energy storage for T1 units, up to 2 for T2, and up to 6 for T3",
    "<LOC loadingtip_0043>To see stealthed underwater units you need water vision or omni",
    "<LOC loadingtip_0044>Keep building available mexes throughout the map/game with your engineers",
    "<LOC loadingtip_0045>Use military units (especially tanks on most maps) to take mexes/map control and counter the enemy",
    "<LOC loadingtip_0046>You should generally use your ACU to secure groups of mexes and engage in combat in the early game",
    "<LOC loadingtip_0047>Don't be too reckless with your ACU (it can be very useful in combat without being suicidal)",
    "<LOC loadingtip_0048>Keep scouting throughout the game (most people don't scout enough)",
    "<LOC loadingtip_0049>Pay enough attention to what you scout",
    "<LOC loadingtip_0050>It is generally better to take battles you will efficiently win and avoid battles you will lose",
    "<LOC loadingtip_0051>Taking the right battles and avoiding the wrong ones is generally especially important in air",
    "<LOC loadingtip_0052>Don't play too zoomed in - there are more important things than perferct adjacency and base layout",
    "<LOC loadingtip_0053>Generally, you should focus on macro more than micro, but still micro some",
    "<LOC loadingtip_0054>Manual reclaim is generally not considered a good use of your time after the early game",
    "<LOC loadingtip_0055>Generally try to avoid having idle units without a good reason, especially in the early game",
    "<LOC loadingtip_0056>Setting up good hotkeys can help you save time to focus more on the game and less on your mouse",
    "<LOC loadingtip_0057>Focus on doing the best you can and learning what you can do better instead of blaming others",
    "<LOC loadingtip_0058>If you scout enough, you should know what the enemy makes and can generally try to counter it",
    "<LOC loadingtip_0059>If the enemy makes a bunch of land units, minimal AA and no planes, bombers could counter them",
    "<LOC loadingtip_0060>If the enemy makes a bunch of PD, you can often go around it, outrange it, or out eco them",
    "<LOC loadingtip_0061>If the enemy spams T1/T2 air, you can generally make interceptors and mobile flak (T2 AA)",
    "<LOC loadingtip_0062>If the enemy eco's a lot more than you, you can generally attack them and take winning battles",
    "<LOC loadingtip_0063>If the enemy turtles hard with minimal map control, you can generally out eco them and win later",
    "<LOC loadingtip_0064>If the enemy acts super aggressively, you can try to bait them into battles that are good for you",
    "<LOC loadingtip_0065>Scout, and try to counter what the enemy builds, how the enemy plays, and where the enemy goes",
    "<LOC loadingtip_0066>You should generally have your engineers use attack move orders for reclaiming",
    "<LOC loadingtip_0067>Manual reclaim can be useful during the very early game if you have nothing better to do",
    "<LOC loadingtip_0068>Patrol is generally worse for reclaiming than attack move is",
    "<LOC loadingtip_0069>Use T1 engineers with attack move orders to get the reclaim from dead unit wrecks from battles",
    "<LOC loadingtip_0070>Fighting battles where you can get the reclaim and your enemies can't matters a lot",
    "<LOC loadingtip_0071>A wreck from a dead unit can yield up to about 81% of the unit's mass cost",
    "<LOC loadingtip_0072>It can be worthwhile to kill/reclaim your old low-tech units to have additional mass",
    "<LOC loadingtip_0073>Think about value and opportunity costs (ie: would you rather have ~16 T1 tanks or 1 T2 mex?)",
    "<LOC loadingtip_0074>Low tech units often do more damage per mass but have less health per mass compared to high tech",
    "<LOC loadingtip_0075>Upgrading a factory costs mass that could've been put into units, so don't upgrade too early",
    "<LOC loadingtip_0076>In team games, be a team player",
    "<LOC loadingtip_0077>If you need help or expect to lose your lane soon, tell your team",
    "<LOC loadingtip_0078>If you don't know what to do next, ask your team what to do",
    "<LOC loadingtip_0079>If you have extra mass and can't spend it fast enough, you can gift it to a teammate who can",
    "<LOC loadingtip_0080>If your opponent is attacking your ally, help your ally or be doing something worth the cost",
    "<LOC loadingtip_0081>If you notice an enemy T4/nuke/etc that your team hasn't noticed, ping/mark it and say something",
    "<LOC loadingtip_0082>Try to coordinate your units with your allies' units when it seems worthwhile",
    "<LOC loadingtip_0083>Having a good attitude can help you to play better, have more fun, and learn more",
    "<LOC loadingtip_0084>You can learn a lot from analyzing the replays of highly skilled players",
    "<LOC loadingtip_0085>Remember to have fun (winning can be enjoyable, but it isn't everything)",
    "<LOC loadingtip_0086>Watch replays of your games to learn what different players did well/poorly to help you improve",
    "<LOC loadingtip_0087>You can ask for advice in the gameplay-and-training channel on the FAF Discord",
    "<LOC loadingtip_0088>The FAF wiki has useful guides that can teach you how to get better at FAF",
    "<LOC loadingtip_0089>Scale your economy (mass, energy, & build power) over time",
    "<LOC loadingtip_0090>Spamming units is often worthwhile, but don't forget to transition to higher tech units",
    "<LOC loadingtip_0091>You can generally spam interceptors against t1 and t2 air, and spam ASF against t3 air",
    "<LOC loadingtip_0092>Avoid stalling energy (don't get to 0 energy storage with a negative net energy income)",
    "<LOC loadingtip_0093>Spend your mass (it's generally inefficient to keep a lot of mass in storage instead of using it)",
    "<LOC loadingtip_0094>Avoid building too much energy (put your resources into things that will be the most useful)",
    "<LOC loadingtip_0095>If you are stalling mass, it might be a good idea to have more of your engineers reclaiming",
    "<LOC loadingtip_0096>It's generally a good idea to expand around the map early on to get mexes, reclaim and map control",
}
