name: Lint
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: 'ps-wow/action-test-repo'
      - name: wow-lint
        uses: 'deploy/fafdevelop'
        with:
            path-to-files: 'lua'