# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Prepare release

on:
  workflow_dispatch:
  push:

jobs:

  # By verifying the snippets we ensure that they're compatible with the bundling
  # process. In the future we can also add spell checking and/or checks for foul words.

  verify:
    name: Verify snippets
    runs-on: ubuntu-latest
    steps:

      # We check out the scripts separate because the branch that we use to
      # generate the changelog may not contain the scripts that we want to work with.
      - name: Checkout scripts
        uses: actions/checkout@v6
        with:
          path: scripts
          sparse-checkout: |
            .github/workflows/scripts/bash

      - name: Checkout snippets
        uses: actions/checkout@v6
        with:
          path: fa
          ref: ${{ inputs.reference }}
          sparse-checkout: |
            changelog/snippets

      - name: Update environment path
        run: |
          ls
          echo "${{ github.workspace }}/scripts/.github/workflows/scripts/bash" >> $GITHUB_PATH

      - name: Verify the changelog snippets
        working-directory: fa/changelog/snippets # script assumes it is in this directory
        run: changelog-verify.sh


  release-preparation:
    name: Prepare files for patch
    runs-on: ubuntu-latest
    needs: verify
    steps:

      - name: Checkout FA repository
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.SSH_FAFOREVER_MACHINE_USER }}
          repository: FAForever/fa
          ref: release-automation

      - name: Determine next patch version
        id: version
        run: |
          CURRENT_VERSION=$(grep 'Version' lua/version.lua | grep -o '[0-9]\+')
          NEXT_VERSION=$((CURRENT_VERSION + 1))
          echo "old_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Metadata
        id: meta
        run: |
          DATE=$(date +%Y-%m-%d)
          BRANCH="changelog${{ steps.version.outputs.version }}"
          
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create branch
        run: |
          if git ls-remote --heads origin "${{ steps.meta.outputs.branch }}" | grep -q ."; then
            echo "Branch '${{ steps.meta.outputs.branch }}' already exists. Aborting workflow."
            exit 1
          fi
          git checkout -b "${{ steps.meta.outputs.branch }}"

      - name: Create changelog post
        working-directory: changelog/snippets
        run: |
          FILE="${{ github.workspace }}/docs/_posts/${{ steps.meta.outputs.date }}-${{ steps.version.outputs.version }}.md"
          ${{ github.workspace }}/.github/workflows/scripts/bash/changelog-combine.sh $FILE
          sed -i "s/XYZW/${{ steps.version.outputs.version }}/g" $FILE

      - name: Update changelogData.lua
        run: |
          sed -i -E "s/(last_version = )[0-9]+/\1${{ steps.version.outputs.version }}/" \
          lua/ui/lobby/changelogData.lua

      - name: Commit changelog
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          
          git add lua/ui/lobby/changelogData.lua docs/_posts
          git commit -m "Add changelog for version ${{ steps.version.outputs.version }}"

      - name: Remove snippets
        run: |
          rm -f changelog/snippets/*.md
          git add changelog/snippets
          git commit -m "Delete changelog snippets"

      - name: Update version number
        run: |
          sed -i "s/${{ steps.version.outputs.old_version }}/${{ steps.version.outputs.version }}/g" lua/version.lua
          sed -i "s/${{ steps.version.outputs.old_version }}/${{ steps.version.outputs.version }}/g" mod_info.lua

          git add lua/version.lua mod_info.lua
          git commit -m "Bump game version to ${{ steps.version.outputs.version }}"

      - name: Push branch
        run: |
          git push origin "${{ steps.meta.outputs.branch }}"

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const version = "${{ steps.version.outputs.version }}";
            const branch = "${{ steps.meta.outputs.branch }}";
            
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Changelog ${version}`,
              head: branch,
              base: "develop",
              body: `Automated changelog and version bump for game version ${version}.`
            });