name: FAF Wiki Generator for unit icons

on:
  workflow_dispatch:

jobs:

  prepare-environment:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      
      steps:
        # Checkout repos, FA repo is sparse checkout as it is quite large
        - name: Checkout Brewlan Wikigen Repository
          uses: actions/checkout@v4
          with:
            repository: The-Balthazar/BrewWikiGen
            ref: master
            path: ./brew-wiki-gen

        - name: Checkout FAF Repository # -png folder doesnt exist yet, confirm location.
          uses: actions/checkout@v4
          with:
            repository: relent0r/fa
            ref: feat/github-wf-icons
            path: ./fa
            sparse-checkout-cone-mode: |
              wiki
              loc
              lua/ui/help/unitscription.lua
              lua/ui/help/tooltips.lua
              lua/sim/AdjacencyBuffs.lua
              lua/system/Blueprints.lua
              units
              projectiles
              textures/ui/common/game/strategicicons
              textures/ui/common/icons/units

        - name: Checkout FAF Wiki Repository
          uses: actions/checkout@v4
          with:
            repository: FAForever/fa.wiki
            ref: master
            path: ./fa.wiki

        - name: Install Lua 5.4
          uses: leafo/gh-actions-lua@v10
          with:
            luaVersion: "5.4"

        - name: Install Image Magick
          run: |
            sudo apt-get install -y imagemagick

        # copy strategic and unit icons and convert them to PNGs. Assume this should be going to the wiki location not the fa repo
        - name: Convert Unit Icons
          run: fa/wiki/icons-convert-units.sh

        - name: Replace run.lua
          run: |
              sudo mv fa/wiki/Run.lua brew-wiki-gen/Run.lua

        - name: Execute lua run
          run: |
            lua brew-wiki-gen/Run.lua --OutputDirectory="fa.wiki/" --WikiGeneratorDirectory="brew-wiki-gen/" --FADirectory="fa/"

        - name: Store the game version
          id: gameVersionJSON # but it is a string here!
          working-directory: app/data
          run: |
              json=`cat ./version.json`
              echo "json=$json" >> $GITHUB_OUTPUT

        - name: Update Wiki repository # but it is a string here!
          working-directory: fa.wiki
          run: |
              git config user.email "administrator@faforever.com"
              git config user.name "FAForever"

              git stage .
              git commit -m "Update generated data to game version ${{ fromJson(steps.gameVersionJSON.outputs.json).version}}"
              git push origin HEAD:master
        

