# Copyright (c) 2024 Willem 'Jip' Wijnia
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Wiki - generate unit pages

on:
  workflow_dispatch:

jobs:

  generate-blueprints:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      
      steps:
        # Checkout repos, FA repo is sparse checkout as it is quite large
        - name: Checkout Brewlan Wikigen Repository
          uses: actions/checkout@v4
          with:
            repository: The-Balthazar/BrewWikiGen
            path: ./brew-wiki-gen

        # FA repo is sparse checkout as it is quite large and we dont won't to incur higher action minutes for no reason
        - name: Checkout FAF Repository # -png folder doesnt exist yet, confirm location.
          uses: actions/checkout@v4
          with:
            path: ./fa
            sparse-checkout-cone-mode: |
              wiki
              loc
              lua/ui/help/unitscription.lua
              lua/ui/help/tooltips.lua
              lua/sim/AdjacencyBuffs.lua
              lua/system/Blueprints.lua
              units/*_unit.bp
              units/*_LOD0.scm
              projectiles

        - name: Checkout FAF Wiki Repository
          uses: actions/checkout@v4
          with:
            repository: FAForever/fa.wiki
            path: ./fa.wiki

        - name: Install Lua 5.4
          uses: leafo/gh-actions-lua@v10
          with:
            luaVersion: "5.4"

        - name: Replace run.lua
          run: |
              sudo mv fa/wiki/Run.lua brew-wiki-gen/Run.lua

        - name: Execute lua run
          run: |
            lua brew-wiki-gen/Run.lua --OutputDirectory="fa.wiki/" --WikiGeneratorDirectory="brew-wiki-gen/" --FADirectory="fa/"

  
        - name: Upload as artifact
          uses: actions/upload-artifact@v4
          with:
            name: Wiki
            path: fa.wiki

        #- name: Store the game version
        #  id: gameVersionJSON # but it is a string here!
        #  working-directory: app/data
        #  run: |
        #      json=`cat ./version.json`
        #      echo "json=$json" >> $GITHUB_OUTPUT

        #- name: Update Wiki repository # but it is a string here!
        #  working-directory: fa.wiki
        #  run: |
        #      git config user.email "administrator@faforever.com"
        #      git config user.name "FAForever"

        #      git stage .
        #      git commit -m "Update generated data to game version ${{ fromJson(steps.gameVersionJSON.outputs.json).version}}"
        #      git push origin HEAD:master
        

