name: FAF Wiki Generator

# not sure if we will use a trigger or if this will be manual? It could trigger on release
on:
  push:
    branches: 
      - 'feat/github-wf-icons'



jobs:

  prepare-environment:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Brewland Wikigen Repository
          uses: actions/checkout@v4
          with:
            repository: The-Balthazar/BrewWikiGen
            ref: master
            path: ./brew-wiki-gen

        - name: Checkout FAF Repository # -png folder doesnt exist yet, confirm location.
          uses: actions/checkout@v4
          with:
            repository: FAForever/fa
            ref: deploy/fafdevelop
            path: ./fa
            sparse-checkout: |
              fa/textures/ui/common/game/strategicicons
              fa/textures/ui/common/icons/units

        - name: Checkout FAF Wiki Repository
          uses: actions/checkout@v4
          with:
            repository: FAForever/fa.wiki
            ref: master
            path: ./fa.wiki

        - name: Install Lua 5.4
          uses: leafo/gh-actions-lua@v10
          with:
            luaVersion: "5.4"

        - name: Install Image Magick
          run: |
            sudo apt-get install -y imagemagick

        - name: find_magick
          run: |
            magick_location=$(command -v magick)
            echo "::set-output name=magick_location::$magick_location"
            echo "Location of magick command: $magick_location"

        # copy strategic and unit icons and convert them to PNGs. Assume this should be going to the wiki location not the fa repo
        - name: Convert Icons
          run: |
            magick_location=$(which magick)
            echo "Location of magick command: $magick_location"
            ${{ steps.find_magick.outputs.magick_location }} mogrify -path "fa/textures/ui/common/game/strategicicons-png" -format png "fa/textures/ui/common/game/strategicicons/*.dds"
            ${{ steps.find_magick.outputs.magick_location }} mogrify -path "fa/textures/ui/common/icons-png" -format png "fa/textures/ui/common/icons/units/*.dds"

        - name: Replace run.lua # tbd
          uses: canastro/copy-file-action@master
          with: #source run.lua file
            source: "placeholder"
            target: "brew-wiki-gen/Run.lua"

        #push action here somewhere
        

