# Copyright (c) 2024 Willem 'Jip' Wijnia
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Wiki - generate changelog

on:
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            changelog/snippets

      - name: Verify the changelog snippets
        working-directory: changelog/snippets # script assumes it is in this directory
        run: |
          ./verify.sh
  update:
    name: Update wiki
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: Checkout FA repository
        uses: actions/checkout@v4
        with:
          path: fa
          sparse-checkout: |
            changelog

      - name: Checkout FA Wiki repository
        uses: actions/checkout@v4
        with:
          repository: faforever/fa.wiki
          path: fa.wiki

      - name: Create the changelog
        working-directory: fa/changelog/snippets # script assumes it is in this directory
        shell: bash
        run: |
          ./combine.sh

      - name: Copy over assets
        run: |
          # do not include the snippets
          rm -rf fa/changelog/snippets

          # remove the old changelogs
          rm -rf fa.wiki/changelog
          mkdir fa.wiki/changelog

          # copy the changelogs for previous releases
          mv fa/changelog/*.md fa.wiki/changelog

      - name: Update the wiki
        run: |
          cd fa.wiki

          git config user.name "FAForever"
          git config user.email "administrator@faforever.com"

          git stage .
          git commit -m "Update changelogs"
          git push origin HEAD:master
